<a href="https://colab.research.google.com/github/nghff/vlm-pca-exercise/blob/main/Raphi_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade vllm

Collecting vllm
  Downloading vllm-0.15.1-cp38-abi3-manylinux_2_31_x86_64.whl.metadata (9.0 kB)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (from vllm) (2025.11.3)
Requirement already satisfied: cachetools in /usr/local/lib/python3.12/dist-packages (from vllm) (7.0.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from vllm) (5.9.5)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from vllm) (0.2.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from vllm) (2.0.2)
Requirement already satisfied: requests>=2.26.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from vllm) (4.67.2)
Collecting blake3 (from vllm)
  Downloading blake3-1.0.8-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.6 kB)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.12/dist-packages (from vllm) (9.0.0)
Collecting transformers<5,>=4.56.0 (from vllm)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: tokenizers>=0.21.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.22.2)
Collecting protobuf>=6.33.5 (from vllm)
  Downloading protobuf-6.33.5-cp39-abi3-manylinux2014_x86_64.whl.metadata (593 bytes)
Requirement already satisfied: fastapi>=0.115.0 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.123.10)
Requirement already satisfied: aiohttp>=3.13.3 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.13.3)
Requirement already satisfied: openai>=1.99.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.16.0)
Requirement already satisfied: pydantic>=2.12.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (2.12.3)
Requirement already satisfied: prometheus_client>=0.18.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.24.1)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from vllm) (11.3.0)
Collecting prometheus-fastapi-instrumentator>=7.0.0 (from vllm)
  Downloading prometheus_fastapi_instrumentator-7.1.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tiktoken>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (0.12.0)
Collecting lm-format-enforcer==0.11.3 (from vllm)
  Downloading lm_format_enforcer-0.11.3-py3-none-any.whl.metadata (17 kB)
Collecting llguidance<1.4.0,>=1.3.0 (from vllm)
  Downloading llguidance-1.3.0-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (10 kB)
Collecting outlines_core==0.2.11 (from vllm)
  Downloading outlines_core-0.2.11-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.8 kB)
Collecting diskcache==5.6.3 (from vllm)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Collecting lark==1.2.2 (from vllm)
  Downloading lark-1.2.2-py3-none-any.whl.metadata (1.8 kB)
Collecting xgrammar==0.1.29 (from vllm)
  Downloading xgrammar-0.1.29-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.8 kB)
Requirement already satisfied: typing_extensions>=4.10 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.15.0)
Requirement already satisfied: filelock>=3.16.1 in /usr/local/lib/python3.12/dist-packages (from vllm) (3.20.3)
Collecting partial-json-parser (from vllm)
  Downloading partial_json_parser-0.2.1.1.post7-py3-none-any.whl.metadata (6.1 kB)
Requirement already satisfied: pyzmq>=25.0.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (26.2.1)
Collecting msgspec (from vllm)
  Downloading msgspec-0.20.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.5 kB)
Collecting gguf>=0.17.0 (from vllm)
  Downloading gguf-0.17.1-py3-none-any.whl.metadata (4.3 kB)
Collecting mistral_common>=1.8.8 (from mistral_common[image]>=1.8.8->vllm)
  Downloading mistral_common-1.9.0-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: opencv-python-headless>=4.13.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (4.13.0.90)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from vllm) (6.0.3)
Requirement already satisfied: six>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from vllm) (1.17.0)
Collecting setuptools<81.0.0,>=77.0.3 (from vllm)
  Downloading setuptools-80.10.2-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: einops in /usr/local/lib/python3.12/dist-packages (from vllm) (0.8.2)
Collecting compressed-tensors==0.13.0 (from vllm)
  Downloading compressed_tensors-0.13.0-py3-none-any.whl.metadata (7.0 kB)
Collecting depyf==0.20.0 (from vllm)
  Downloading depyf-0.20.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: cloudpickle in /usr/local/lib/python3.12/dist-packages (from vllm) (3.1.2)
Requirement already satisfied: watchfiles in /usr/local/lib/python3.12/dist-packages (from vllm) (1.1.1)
Requirement already satisfied: python-json-logger in /usr/local/lib/python3.12/dist-packages (from vllm) (4.0.0)
Collecting ninja (from vllm)
  Downloading ninja-1.13.0-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (5.1 kB)
Collecting pybase64 (from vllm)
  Downloading pybase64-1.4.3-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (8.7 kB)
Collecting cbor2 (from vllm)
  Downloading cbor2-5.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Collecting ijson (from vllm)
  Downloading ijson-3.4.0.post0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (23 kB)
Collecting setproctitle (from vllm)
  Downloading setproctitle-1.3.7-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (10 kB)
Collecting openai-harmony>=0.0.3 (from vllm)
  Downloading openai_harmony-0.0.8-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.0 kB)
Collecting anthropic>=0.71.0 (from vllm)
  Downloading anthropic-0.78.0-py3-none-any.whl.metadata (28 kB)
Collecting model-hosting-container-standards<1.0.0,>=0.1.13 (from vllm)
  Downloading model_hosting_container_standards-0.1.13-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: mcp in /usr/local/lib/python3.12/dist-packages (from vllm) (1.26.0)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from vllm) (1.76.0)
Collecting grpcio-reflection (from vllm)
  Downloading grpcio_reflection-1.78.0-py3-none-any.whl.metadata (1.2 kB)
Collecting numba==0.61.2 (from vllm)
  Downloading numba-0.61.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (2.8 kB)
Collecting ray>=2.48.0 (from ray[cgraph]>=2.48.0->vllm)
  Downloading ray-2.53.0-cp312-cp312-manylinux2014_x86_64.whl.metadata (22 kB)
Collecting torch==2.9.1 (from vllm)
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Collecting torchaudio==2.9.1 (from vllm)
  Downloading torchaudio-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (6.9 kB)
Collecting torchvision==0.24.1 (from vllm)
  Downloading torchvision-0.24.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Collecting flashinfer-python==0.6.1 (from vllm)
  Downloading flashinfer_python-0.6.1-py3-none-any.whl.metadata (10 kB)
Collecting loguru (from compressed-tensors==0.13.0->vllm)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Collecting astor (from depyf==0.20.0->vllm)
  Downloading astor-0.8.1-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: dill in /usr/local/lib/python3.12/dist-packages (from depyf==0.20.0->vllm) (0.3.8)
Collecting apache-tvm-ffi!=0.1.8,!=0.1.8.post0,<0.2,>=0.1.6 (from flashinfer-python==0.6.1->vllm)
  Downloading apache_tvm_ffi-0.1.8.post2-cp312-abi3-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.4 kB)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.1->vllm) (8.3.1)
Collecting nvidia-cudnn-frontend>=1.13.0 (from flashinfer-python==0.6.1->vllm)
  Downloading nvidia_cudnn_frontend-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (4.4 kB)
Collecting nvidia-cutlass-dsl>=4.3.4 (from flashinfer-python==0.6.1->vllm)
  Downloading nvidia_cutlass_dsl-4.3.5-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (2.6 kB)
Requirement already satisfied: nvidia-ml-py in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.1->vllm) (13.590.48)
Requirement already satisfied: packaging>=24.2 in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.1->vllm) (26.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.12/dist-packages (from flashinfer-python==0.6.1->vllm) (0.9.0)
Collecting interegular>=0.3.2 (from lm-format-enforcer==0.11.3->vllm)
  Downloading interegular-0.3.3-py37-none-any.whl.metadata (3.0 kB)
Collecting llvmlite<0.45,>=0.44.0dev0 (from numba==0.61.2->vllm)
  Downloading llvmlite-0.44.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.0 kB)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (2025.3.0)
Collecting nvidia-cuda-nvrtc-cu12==12.8.93 (from torch==2.9.1->vllm)
  Downloading nvidia_cuda_nvrtc_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-runtime-cu12==12.8.90 (from torch==2.9.1->vllm)
  Downloading nvidia_cuda_runtime_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cuda-cupti-cu12==12.8.90 (from torch==2.9.1->vllm)
  Downloading nvidia_cuda_cupti_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (9.10.2.21)
Collecting nvidia-cublas-cu12==12.8.4.1 (from torch==2.9.1->vllm)
  Downloading nvidia_cublas_cu12-12.8.4.1-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufft-cu12==11.3.3.83 (from torch==2.9.1->vllm)
  Downloading nvidia_cufft_cu12-11.3.3.83-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-curand-cu12==10.3.9.90 (from torch==2.9.1->vllm)
  Downloading nvidia_curand_cu12-10.3.9.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cusolver-cu12==11.7.3.90 (from torch==2.9.1->vllm)
  Downloading nvidia_cusolver_cu12-11.7.3.90-py3-none-manylinux_2_27_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-cusparse-cu12==12.5.8.93 (from torch==2.9.1->vllm)
  Downloading nvidia_cusparse_cu12-12.5.8.93-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch==2.9.1->vllm) (3.3.20)
Collecting nvidia-nvtx-cu12==12.8.90 (from torch==2.9.1->vllm)
  Downloading nvidia_nvtx_cu12-12.8.90-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvjitlink-cu12==12.8.93 (from torch==2.9.1->vllm)
  Downloading nvidia_nvjitlink_cu12-12.8.93-py3-none-manylinux2010_x86_64.manylinux_2_12_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-cufile-cu12==1.13.1.3 (from torch==2.9.1->vllm)
  Downloading nvidia_cufile_cu12-1.13.1.3-py3-none-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (1.7 kB)
Collecting triton==3.5.1 (from torch==2.9.1->vllm)
  Downloading triton-3.5.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (1.7 kB)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp>=3.13.3->vllm) (1.22.0)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (4.12.1)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (1.9.0)
Requirement already satisfied: docstring-parser<1,>=0.15 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (0.17.0)
Requirement already satisfied: httpx<1,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (0.28.1)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (0.13.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from anthropic>=0.71.0->vllm) (1.3.1)
Requirement already satisfied: starlette<0.51.0,>=0.40.0 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.50.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi>=0.115.0->fastapi[standard]>=0.115.0->vllm) (0.0.4)
Collecting fastapi-cli>=0.0.8 (from fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
  Downloading fastapi_cli-0.0.20-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: python-multipart>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from fastapi[standard]>=0.115.0->vllm) (0.0.22)
Collecting email-validator>=2.0.0 (from fastapi[standard]>=0.115.0->vllm)
  Downloading email_validator-2.3.0-py3-none-any.whl.metadata (26 kB)
Requirement already satisfied: uvicorn>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from uvicorn[standard]>=0.12.0; extra == "standard"->fastapi[standard]>=0.115.0->vllm) (0.40.0)
Requirement already satisfied: jsonschema>=4.21.1 in /usr/local/lib/python3.12/dist-packages (from mistral_common>=1.8.8->mistral_common[image]>=1.8.8->vllm) (4.26.0)
Collecting pydantic-extra-types>=2.10.5 (from pydantic-extra-types[pycountry]>=2.10.5->mistral_common>=1.8.8->mistral_common[image]>=1.8.8->vllm)
  Downloading pydantic_extra_types-2.11.0-py3-none-any.whl.metadata (4.0 kB)
Collecting jmespath (from model-hosting-container-standards<1.0.0,>=0.1.13->vllm)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting supervisor>=4.2.0 (from model-hosting-container-standards<1.0.0,>=0.1.13->vllm)
  Downloading supervisor-4.3.0-py2.py3-none-any.whl.metadata (87 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 87.9/87.9 kB 9.7 MB/s eta 0:00:00
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic>=2.12.0->vllm) (0.4.2)
Requirement already satisfied: msgpack<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from ray>=2.48.0->ray[cgraph]>=2.48.0->vllm) (1.1.2)
Requirement already satisfied: cupy-cuda12x in /usr/local/lib/python3.12/dist-packages (from ray[cgraph]>=2.48.0->vllm) (13.6.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.26.0->vllm) (2026.1.4)
Requirement already satisfied: huggingface-hub<2.0,>=0.16.4 in /usr/local/lib/python3.12/dist-packages (from tokenizers>=0.21.1->vllm) (1.3.7)
Collecting huggingface-hub<2.0,>=0.16.4 (from tokenizers>=0.21.1->vllm)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5,>=4.56.0->vllm) (0.7.0)
Collecting grpcio (from vllm)
  Downloading grpcio-1.78.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: httpx-sse>=0.4 in /usr/local/lib/python3.12/dist-packages (from mcp->vllm) (0.4.3)
Requirement already satisfied: pydantic-settings>=2.5.2 in /usr/local/lib/python3.12/dist-packages (from mcp->vllm) (2.12.0)
Requirement already satisfied: pyjwt>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyjwt[crypto]>=2.10.1->mcp->vllm) (2.11.0)
Requirement already satisfied: sse-starlette>=1.6.1 in /usr/local/lib/python3.12/dist-packages (from mcp->vllm) (3.2.0)
Collecting dnspython>=2.0.0 (from email-validator>=2.0.0->fastapi[standard]>=0.115.0->vllm)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: typer>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm) (0.21.1)
Collecting rich-toolkit>=0.14.8 (from fastapi-cli>=0.0.8->fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
  Downloading rich_toolkit-0.18.1-py3-none-any.whl.metadata (1.0 kB)
Collecting fastapi-cloud-cli>=0.1.1 (from fastapi-cli[standard]>=0.0.8; extra == "standard"->fastapi[standard]>=0.115.0->vllm)
  Downloading fastapi_cloud_cli-0.11.0-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.25.0->anthropic>=0.71.0->vllm) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.25.0->anthropic>=0.71.0->vllm) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.16.4->tokenizers>=0.21.1->vllm) (1.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.9.1->vllm) (3.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.21.1->mistral_common>=1.8.8->mistral_common[image]>=1.8.8->vllm) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=4.21.1->mistral_common>=1.8.8->mistral_common[image]>=1.8.8->vllm) (0.37.0)

In [ ]:
import torch
from torch.utils.data import Dataset, DataLoader
from torch.nn.modules import padding
from torch.utils.data._utils.collate import default_collate

from transformers import AutoTokenizer, AutoProcessor, AutoModelForImageTextToText
from PIL import Image, UnidentifiedImageError

import io, os, base64, requests
import regex as re
from typing import List
import numpy as np
import pandas as pd
from hashlib import sha256
import sys

import time
from tqdm import tqdm as tqdm

import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

from google.colab import drive
drive.mount('/content/drive')

DRIVE_DIR = '/content/drive/'
SAVE_DIR = os.path.join(DRIVE_DIR, 'MyDrive/Raphi_Task_Data')
if not os.path.exists(SAVE_DIR):
  os.makedirs(SAVE_DIR)

DATA_PORTION = 1

model_id = "Qwen/Qwen3-VL-2B-Instruct"
#model_id = "llava-hf/llava-1.5-7b-hf"
#model_id = "allenai/Molmo2-8B"

RESULTS_SAVE_DIR = os.path.join(SAVE_DIR, model_id)
if not os.path.exists(RESULTS_SAVE_DIR):
  os.makedirs(RESULTS_SAVE_DIR)

Mounted at /content/drive

In [ ]:
def save_df(name, df, show_df=False):
    df_path = os.path.join(RESULTS_SAVE_DIR, f'{name}.pkl')
    df.to_pickle(df_path)

    if show_df:
        display(df)

def load_df(name):
    df_path = os.path.join(RESULTS_SAVE_DIR, f'{name}.pkl')
    return pd.read_pickle(df_path)

### Dataset implementation for pixmo dataset

In [ ]:
def pixmo_collate_fn(processor, timeout=10, max_length: int = 4096):
    def collate_fn(batch):
        messages_list = [b["messages"] for b in batch]
        targets = torch.tensor([b["target_count"] for b in batch])
        bad_messages_idx = []

        for i in range(len(messages_list)):
            for message in messages_list[i]:
                if message["role"] != "user":
                    continue
                for content in message["content"]:
                    if content["type"] != "image":
                        continue
                    img_url = content["image"]

                    if img_url.startswith("http://") or img_url.startswith("https://"):
                        try:
                            r = requests.get(img_url, timeout=timeout, allow_redirects=True)
                            r.raise_for_status()
                        except:
                            print(f"request failed: {img_url}")
                            bad_messages_idx.append(i)
                            break
                        ct = (r.headers.get("content-type") or "").lower()

                        if "image" not in ct:
                            print(f"filtered: {img_url}")
                            bad_messages_idx.append(i)
                            break
                    else:
                        print(f"filtered: {img_url}")
                        bad_messages_idx.append(i)
                        break
                break

        # remove messages with failed images
        for idx in sorted(bad_messages_idx, reverse=True):
            targets = torch.cat([targets[:idx], targets[idx+1:]])
            del messages_list[idx]

        print(f'num messages: {len(messages_list)}')

        inputs = processor.apply_chat_template(
            messages_list,
            tokenize=True,
            continue_final_message=True,
            return_dict=True,
            return_tensors="pt",
            padding='longest'
        )

        inputs["target_count"] = targets
        return inputs
    return collate_fn

class pixmoDataset(Dataset):
  splits = {
    'val': 'validation-00000-of-00001.parquet',
    'train': 'train-00000-of-00001.parquet',
    'test': 'test-00000-of-00001.parquet'
  }

  def __init__(self,
               split: str,
               processor: AutoProcessor,
               portion=1.0, max_length=4096,
               **kwargs):
    if split == "validation":
      split = "val"
    if split not in pixmoDataset.splits:
      raise ValueError("'split' not recognized in dataset constructor")

    split_file = pixmoDataset.splits[split]
    self.data = pd.read_parquet("hf://datasets/allenai/pixmo-count/data/" + split_file)
    self.data = self.data.filter(items=['image_url', 'label', 'count'])
    self.processor = processor
    self.portion = portion
    self.max_length = max_length
    if 'filter_fn' in kwargs:
      self.data = kwargs['filter_fn'](self.data)

  def __len__(self):
    return int(len(self.data) * self.portion)

  def __getitem__(self, idx):
        row = self.data.iloc[idx]
        label = row["label"]
        image = row["image_url"]
        target = int(row["count"])

        messages = [
            {
                "role": "user",
                "content": [
                    {"type": "image", "image": image},
                    {"type": "text", "text": f"How many {label} are in this photo?"},
                ],
            },
            {
                "role": "assistant",
                "content": [{"type": "text", "text": f"The number of {label} is: "}],
            },
        ]

        return {"messages": messages, "target_count": target}

### Evaluator

In [ ]:
# define metrics
def sanitize_pairs(pred: List[str], target: List[str]):
  p = []
  t = []
  misfits = []
  for i in range(len(pred)):
    if pred[i] != '':
      p.append(int(re.sub(r'[^\d]+', '', pred[i])))
      t.append(target[i])
    else:
      misfits.append((pred[i], target[i]))
  return p, t, misfits

def accuracy(pred: List[int], target: List[int]):
  return np.mean(pred == target)

def mean_error(pred: List[int], target: List[int]):
  return np.mean(np.abs(pred - target))

def mean_squared_error(pred: List[int], target: List[int]):
  return np.mean((pred - target)**2)

In [ ]:
class Evaluator:
  def __init__(self,
               metric_fns={},
               batch_size=4,
               shuffle=False,
               collate_fn=None,
               token_allowance=2,
               callbacks=[]):
    self.metric_fns = metric_fns
    self.batch_size = batch_size
    self.shuffle = shuffle
    self.collate_fn = collate_fn
    self.max_new_tokens = token_allowance
    self.callbacks = callbacks

  def __call__(self, model, processor, dataset, **kwargs):
    return self.evaluate(model, processor, dataset, **kwargs)

  def evaluate(self, model, processor, dataset, **kwargs):
    dataloader = DataLoader(dataset, batch_size=self.batch_size, shuffle=self.shuffle, collate_fn=self.collate_fn)
    all_preds = []
    all_targets = []
    all_inputs = []
    all_misfits = []
    dl_progress = tqdm(dataloader)

    model.eval()
    with torch.inference_mode():
        for batch in dl_progress:
            target_counts = batch.pop('target_count')
            target_counts = [count.item() for count in target_counts]

            inputs = batch
            inputs = {k: v.to(model.device, non_blocking=True) for k, v in inputs.items()}

            output = model.generate(
                **inputs,
                max_new_tokens=self.max_new_tokens,
                num_beams=1,
                do_sample=False,
                return_dict_in_generate=True,
                output_scores=False,
                output_hidden_states=kwargs.get('needs_hidden_states', False),
                output_attentions=kwargs.get('needs_attentions', False)
            )

            generated_ids_trimmed = [
                out_ids[len(in_ids) :] for in_ids, out_ids in zip(inputs['input_ids'], output['sequences'])
            ]
            generated_strs = processor.batch_decode(
                generated_ids_trimmed, skip_special_tokens=True, clean_up_tokenization_spaces=False
            )

            generated_preds, target_counts, misfits = sanitize_pairs(generated_strs, target_counts)

            all_preds.extend(generated_preds)
            all_targets.extend(target_counts)
            all_inputs.extend([input_ids for input_ids in inputs['input_ids']])
            all_misfits.extend(misfits)

            print(f'preds: {generated_preds}')
            print(f'targets: {target_counts}')
            for callback in self.callbacks:
                callback(
                    inputs,
                    target_counts,
                    generated_preds,
                    output['hidden_states'] if 'hidden_states' in output else None,
                    output['attentions'] if 'attentions' in output else None
                )

    metrics = {}
    for name, fn in metric_fns.items():
        metrics[name] = fn(np.array(all_preds), np.array(all_targets))

    return {
        'metrics': metrics,
        'all_inputs': all_inputs,
        'all_preds': all_preds,
        'all_targets': all_targets,
        'all_misfits': all_misfits
    }

## Evaluation

### Run evaluation

In [ ]:
load_params = {
    'Qwen/Qwen3-VL-2B-Instruct': {
        'dtype': torch.bfloat16,
        'device_map': "auto"
    },

    'llava-hf/llava-1.5-7b-hf': {
        'torch_dtype': torch.float16,
        'low_cpu_mem_usage': True
    },

    'allenai/Molmo2-8B': {
        'dtype': "auto",
        'device_map': "auto",
        'trust_remote_code': True
    }
}

model = AutoModelForImageTextToText.from_pretrained(
     model_id, **load_params[model_id]
)

processor = AutoProcessor.from_pretrained(model_id, trust_remote_code = True)
processor.tokenizer.padding_side = "left"

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/4.26G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/625 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/269 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

preprocessor_config.json:   0%|          | 0.00/390 [00:00<?, ?B/s]

chat_template.json: 0.00B [00:00, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

video_preprocessor_config.json:   0%|          | 0.00/385 [00:00<?, ?B/s]

In [ ]:
test_dataset = pixmoDataset(split='test', processor=processor, portion=DATA_PORTION)
print(len(test_dataset))

metric_fns = {
    "accuracy": accuracy,
    "mean_error": mean_error,
    "mean_squared_error": mean_squared_error
}

540

In [ ]:
evaluator = Evaluator(
    metric_fns=metric_fns,
    batch_size=4,
    shuffle=False,
    collate_fn=pixmo_collate_fn(processor)
)
results = evaluator(model, processor, test_dataset)

# show misfits
misfits_df = pd.DataFrame(results['all_misfits'], columns=['pred', 'target'])
save_df('all_misfits', misfits_df, show_df=True)

# display results
results_df = pd.DataFrame(results['metrics'], index=[0])
save_df('results', results_df, show_df=True)
results_df

# save all input-pred-target pairs
all_df = pd.DataFrame(zip(results['all_inputs'], results['all_preds'], results['all_targets']), columns=['input', 'pred', 'target'])
save_df('all_input_pred_target_pairs', all_df, show_df=False)

  0%|          | 0/135 [00:00<?, ?it/s]

num messages: 4

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
  1%|          | 1/135 [00:23<52:28, 23.50s/it]

preds: [5, 9, 9, 4]
targets: [5, 10, 10, 4]
num messages: 4

  1%|▏         | 2/135 [00:59<1:08:54, 31.08s/it]

preds: [10, 5, 6, 6]
targets: [10, 5, 6, 9]
num messages: 4

  2%|▏         | 3/135 [01:41<1:18:50, 35.84s/it]

preds: [8, 4, 6, 3]
targets: [9, 4, 6, 3]
num messages: 4

  3%|▎         | 4/135 [02:15<1:16:56, 35.24s/it]

preds: [3, 7, 5, 3]
targets: [3, 7, 5, 3]
request failed: https://live.staticflickr.com/7076/7168922099_cbb6717c58_h.jpg
num messages: 3

  4%|▎         | 5/135 [02:34<1:03:30, 29.31s/it]

preds: [8, 6, 10]
targets: [9, 5, 7]
num messages: 4

  4%|▍         | 6/135 [03:20<1:15:13, 34.99s/it]

preds: [3, 10, 9, 3]
targets: [3, 10, 9, 3]
num messages: 4

  5%|▌         | 7/135 [04:38<1:44:28, 48.97s/it]

preds: [3, 5, 8, 3]
targets: [3, 5, 9, 3]
request failed: https://live.staticflickr.com/7677/28123388986_5553da753a_h.jpg
num messages: 3

  6%|▌         | 8/135 [05:03<1:27:50, 41.50s/it]

preds: [9, 10, 5]
targets: [10, 8, 6]
num messages: 4

  7%|▋         | 9/135 [05:30<1:17:34, 36.94s/it]

preds: [4, 7, 3, 8]
targets: [4, 7, 3, 9]
num messages: 4

  7%|▋         | 10/135 [06:07<1:17:09, 37.04s/it]

preds: [5, 9, 3, 10]
targets: [5, 9, 4, 9]
num messages: 4

  8%|▊         | 11/135 [06:48<1:18:32, 38.00s/it]

preds: [5, 5, 1, 10]
targets: [5, 5, 2, 10]
num messages: 4

  9%|▉         | 12/135 [07:27<1:18:38, 38.36s/it]

preds: [6, 10, 10, 6]
targets: [5, 10, 10, 8]
request failed: https://live.staticflickr.com/8472/29384099650_98f04a84c2_b.jpg
num messages: 3

 10%|▉         | 13/135 [07:56<1:12:26, 35.62s/it]

preds: [6, 8, 3]
targets: [6, 8, 3]
num messages: 4

 10%|█         | 14/135 [08:36<1:14:37, 37.00s/it]

preds: [4, 7, 8, 9]
targets: [4, 8, 9, 10]
num messages: 4

 11%|█         | 15/135 [08:49<59:31, 29.76s/it]

preds: [9, 4, 2, 9]
targets: [10, 4, 2, 10]
num messages: 4

 12%|█▏        | 16/135 [09:34<1:07:52, 34.22s/it]

preds: [3, 6, 2, 8]
targets: [2, 6, 2, 8]
request failed: https://live.staticflickr.com/3743/11220304725_1b3025702f_h.jpg
num messages: 3

 13%|█▎        | 17/135 [09:55<59:40, 30.34s/it]

preds: [8, 2, 4]
targets: [10, 2, 5]
num messages: 4

 13%|█▎        | 18/135 [10:18<54:38, 28.02s/it]

preds: [4, 6, 8, 10]
targets: [4, 6, 9, 10]
num messages: 4

 14%|█▍        | 19/135 [10:50<56:40, 29.31s/it]

preds: [4, 8, 2, 6]
targets: [4, 10, 2, 7]
num messages: 4

 15%|█▍        | 20/135 [11:30<1:02:29, 32.60s/it]

preds: [9, 8, 6, 5]
targets: [10, 8, 8, 5]
num messages: 4

 16%|█▌        | 21/135 [12:04<1:02:40, 32.99s/it]

preds: [7, 2, 2, 5]
targets: [6, 2, 2, 5]
num messages: 4

 16%|█▋        | 22/135 [12:29<57:09, 30.35s/it]

preds: [4, 10, 5, 6]
targets: [4, 10, 5, 7]
num messages: 4

 17%|█▋        | 23/135 [12:57<55:22, 29.67s/it]

preds: [7, 7, 8, 9]
targets: [7, 8, 8, 10]
num messages: 4

 18%|█▊        | 24/135 [13:43<1:04:15, 34.73s/it]

preds: [9, 8, 6, 3]
targets: [9, 8, 6, 3]
num messages: 4

 19%|█▊        | 25/135 [14:24<1:07:00, 36.55s/it]

preds: [3, 3, 8, 5]
targets: [4, 4, 9, 6]
num messages: 4

 19%|█▉        | 26/135 [14:49<1:00:11, 33.13s/it]

preds: [0, 2, 5, 8]
targets: [5, 2, 9, 8]
num messages: 4

 20%|██        | 27/135 [15:23<59:55, 33.29s/it]

preds: [5, 2, 9, 3]
targets: [5, 2, 9, 3]
num messages: 4

 21%|██        | 28/135 [15:44<53:11, 29.82s/it]

preds: [2, 5, 5, 4]
targets: [4, 5, 5, 4]
num messages: 4

 21%|██▏       | 29/135 [16:07<48:38, 27.53s/it]

preds: [3, 7, 5, 6]
targets: [3, 8, 5, 8]
num messages: 4

 22%|██▏       | 30/135 [16:39<50:49, 29.04s/it]

preds: [8, 5, 5, 5]
targets: [9, 9, 5, 5]
num messages: 4

 23%|██▎       | 31/135 [17:16<54:15, 31.31s/it]

preds: [8, 3, 2, 4]
targets: [9, 3, 2, 4]
num messages: 4

 24%|██▎       | 32/135 [18:28<1:14:32, 43.42s/it]

preds: [3, 10, 3, 10]
targets: [3, 10, 3, 9]
num messages: 4

 24%|██▍       | 33/135 [19:00<1:08:20, 40.20s/it]

preds: [3, 9, 8, 6]
targets: [3, 10, 7, 7]
num messages: 4

 25%|██▌       | 34/135 [19:37<1:05:44, 39.05s/it]

preds: [7, 5, 2, 7]
targets: [7, 5, 6, 6]
num messages: 4

 26%|██▌       | 35/135 [19:59<56:38, 33.98s/it]

preds: [6, 5, 6, 8]
targets: [8, 5, 6, 9]
request failed: https://live.staticflickr.com/7024/13759965593_55c43fe18a_h.jpg
num messages: 3

 27%|██▋       | 36/135 [20:26<52:36, 31.89s/it]

preds: [5, 4, 5]
targets: [6, 5, 6]
request failed: https://live.staticflickr.com/4861/39927545953_284cbffd0f_h.jpg
num messages: 3

 27%|██▋       | 37/135 [20:44<45:30, 27.86s/it]

preds: [9, 4, 5]
targets: [9, 4, 7]
num messages: 4

 28%|██▊       | 38/135 [21:21<49:10, 30.42s/it]

preds: [3, 6, 7, 10]
targets: [3, 6, 10, 10]
request failed: https://live.staticflickr.com/5682/20888924293_e2a9681e1c_h.jpg
num messages: 3

 29%|██▉       | 39/135 [21:39<43:00, 26.88s/it]

preds: [6, 10, 10]
targets: [6, 9, 10]
num messages: 4

 30%|██▉       | 40/135 [22:03<40:53, 25.83s/it]

preds: [2, 7, 6, 8]
targets: [2, 7, 8, 8]
num messages: 4

 30%|███       | 41/135 [22:36<43:58, 28.07s/it]

preds: [6, 8, 6, 4]
targets: [6, 9, 7, 4]
num messages: 4

 31%|███       | 42/135 [23:08<45:19, 29.24s/it]

preds: [3, 8, 8, 5]
targets: [3, 7, 10, 4]
num messages: 4

 32%|███▏      | 43/135 [23:42<47:01, 30.67s/it]

preds: [4, 3, 10, 10]
targets: [4, 3, 10, 9]
num messages: 4

 33%|███▎      | 44/135 [24:19<49:18, 32.51s/it]

preds: [8, 2, 3, 2]
targets: [8, 2, 3, 2]
num messages: 4

 33%|███▎      | 45/135 [24:25<36:56, 24.63s/it]

preds: [2, 3, 4, 4]
targets: [2, 3, 4, 4]
num messages: 4

 34%|███▍      | 46/135 [24:46<35:07, 23.68s/it]

preds: [5, 3, 5, 3]
targets: [5, 3, 5, 4]
num messages: 4

 35%|███▍      | 47/135 [25:26<41:53, 28.56s/it]

preds: [2, 1, 6, 5]
targets: [3, 10, 9, 6]
num messages: 4

 36%|███▌      | 48/135 [26:03<45:01, 31.05s/it]

preds: [9, 9, 2, 5]
targets: [10, 9, 2, 5]
num messages: 4

 36%|███▋      | 49/135 [26:34<44:30, 31.06s/it]

preds: [4, 6, 10, 6]
targets: [5, 5, 10, 6]
num messages: 4

 37%|███▋      | 50/135 [27:14<47:37, 33.62s/it]

preds: [4, 10, 7, 3]
targets: [8, 9, 7, 4]
num messages: 4

 38%|███▊      | 51/135 [28:05<54:21, 38.83s/it]

preds: [12, 8, 5, 3]
targets: [10, 9, 6, 4]
num messages: 4

 39%|███▊      | 52/135 [28:42<53:02, 38.34s/it]

preds: [4, 4, 6, 6]
targets: [4, 5, 6, 6]
request failed: https://live.staticflickr.com/7917/45977844995_3d84fd7256_h.jpg
num messages: 3

 39%|███▉      | 53/135 [28:55<42:03, 30.78s/it]

preds: [2, 7, 4]
targets: [2, 9, 4]
num messages: 4

 40%|████      | 54/135 [29:28<42:17, 31.33s/it]

preds: [6, 8, 3, 8]
targets: [6, 8, 3, 10]
num messages: 4

 41%|████      | 55/135 [29:57<40:50, 30.64s/it]

preds: [6, 5, 5, 5]
targets: [7, 7, 7, 7]
num messages: 4

 41%|████▏     | 56/135 [30:34<42:56, 32.61s/it]

preds: [3, 9, 9, 2]
targets: [3, 9, 9, 2]
request failed: https://live.staticflickr.com/4887/40068970103_a201b56f97_h.jpg
num messages: 3

 42%|████▏     | 57/135 [31:06<42:20, 32.57s/it]

preds: [9, 8, 6]
targets: [9, 9, 6]
num messages: 4

 43%|████▎     | 58/135 [31:53<47:17, 36.85s/it]

preds: [4, 8, 6, 2]
targets: [4, 8, 6, 2]
num messages: 4

 44%|████▎     | 59/135 [32:14<40:32, 32.01s/it]

preds: [7, 0, 6, 5]
targets: [7, 10, 7, 5]
num messages: 4

 44%|████▍     | 60/135 [32:40<37:40, 30.14s/it]

preds: [5, 8, 2, 6]
targets: [6, 7, 2, 6]
num messages: 4

 45%|████▌     | 61/135 [33:16<39:16, 31.84s/it]

preds: [5, 3, 6, 5]
targets: [5, 3, 8, 5]
num messages: 4

 46%|████▌     | 62/135 [33:55<41:22, 34.01s/it]

preds: [3, 8, 6, 4]
targets: [3, 7, 7, 5]
num messages: 4

 47%|████▋     | 63/135 [34:22<38:14, 31.87s/it]

preds: [8, 6, 2, 4]
targets: [8, 6, 2, 7]
num messages: 4

 47%|████▋     | 64/135 [35:04<41:26, 35.02s/it]

preds: [2, 8, 3, 10]
targets: [2, 9, 4, 10]
num messages: 4

 48%|████▊     | 65/135 [35:41<41:43, 35.76s/it]

preds: [2, 8, 8, 10]
targets: [2, 6, 10, 9]
num messages: 4

 49%|████▉     | 66/135 [36:27<44:25, 38.63s/it]

preds: [2, 9, 2, 10]
targets: [3, 9, 2, 8]
num messages: 4

 50%|████▉     | 67/135 [37:09<44:57, 39.66s/it]

preds: [10, 7, 9, 4]
targets: [10, 8, 10, 5]
num messages: 4

 50%|█████     | 68/135 [37:42<42:09, 37.76s/it]

preds: [2, 9, 3, 4]
targets: [2, 10, 3, 4]
num messages: 4

 51%|█████     | 69/135 [38:21<41:56, 38.12s/it]

preds: [6, 9, 6, 9]
targets: [9, 8, 7, 9]
num messages: 4

 52%|█████▏    | 70/135 [38:49<37:55, 35.01s/it]

preds: [6, 3, 6, 2]
targets: [5, 4, 7, 2]
num messages: 4

 53%|█████▎    | 71/135 [39:11<33:18, 31.23s/it]

preds: [3, 10, 4, 3]
targets: [3, 10, 4, 3]
num messages: 4

 53%|█████▎    | 72/135 [39:33<29:43, 28.31s/it]

preds: [2, 7, 4, 3]
targets: [2, 7, 4, 3]
num messages: 4

 54%|█████▍    | 73/135 [40:04<30:12, 29.23s/it]

preds: [5, 6, 4, 5]
targets: [5, 6, 4, 5]
request failed: https://live.staticflickr.com/65535/49491555826_e467a1d33a_h.jpg
num messages: 3

 55%|█████▍    | 74/135 [40:14<23:43, 23.34s/it]

preds: [9, 10, 4]
targets: [9, 10, 4]
num messages: 4

 56%|█████▌    | 75/135 [40:57<29:13, 29.22s/it]

preds: [3, 8, 7, 7]
targets: [3, 8, 8, 7]
num messages: 4

 56%|█████▋    | 76/135 [41:34<31:08, 31.66s/it]

preds: [2, 8, 9, 9]
targets: [2, 8, 10, 9]
num messages: 4

 57%|█████▋    | 77/135 [42:57<45:29, 47.06s/it]

preds: [5, 8, 3, 3]
targets: [5, 8, 6, 3]
num messages: 4

 58%|█████▊    | 78/135 [43:33<41:26, 43.62s/it]

preds: [9, 7, 6, 2]
targets: [9, 8, 6, 3]
num messages: 4

 59%|█████▊    | 79/135 [44:10<38:51, 41.63s/it]

preds: [5, 3, 6, 6]
targets: [6, 5, 7, 6]
num messages: 4

 59%|█████▉    | 80/135 [44:45<36:28, 39.79s/it]

preds: [6, 10, 5, 3]
targets: [7, 10, 6, 4]
num messages: 4

 60%|██████    | 81/135 [45:21<34:43, 38.58s/it]

preds: [4, 5, 5, 9]
targets: [4, 5, 5, 9]
num messages: 4

 61%|██████    | 82/135 [45:53<32:29, 36.77s/it]

preds: [10, 2, 10, 6]
targets: [10, 3, 10, 5]
num messages: 4

 61%|██████▏   | 83/135 [47:16<43:43, 50.46s/it]

preds: [3, 2, 4, 3]
targets: [3, 2, 5, 3]
num messages: 4

 62%|██████▏   | 84/135 [47:41<36:34, 43.02s/it]

preds: [6, 5, 5, 8]
targets: [6, 6, 5, 8]
num messages: 4

 63%|██████▎   | 85/135 [48:28<36:40, 44.00s/it]

preds: [10, 10, 8, 6]
targets: [10, 10, 8, 6]
num messages: 4

 64%|██████▎   | 86/135 [49:19<37:38, 46.10s/it]

preds: [7, 9, 7, 7]
targets: [6, 9, 7, 7]
num messages: 4

 64%|██████▍   | 87/135 [49:45<32:04, 40.10s/it]

preds: [6, 5, 5, 8]
targets: [6, 5, 7, 8]
num messages: 4

 65%|██████▌   | 88/135 [50:15<29:02, 37.08s/it]

preds: [9, 8, 1, 2]
targets: [9, 9, 3, 2]
num messages: 4

 66%|██████▌   | 89/135 [51:01<30:34, 39.89s/it]

preds: [3, 10, 8, 2]
targets: [3, 10, 8, 2]
request failed: https://live.staticflickr.com/4878/31951152047_4e99d27d8f_h.jpg
num messages: 3

 67%|██████▋   | 90/135 [51:20<25:05, 33.46s/it]

preds: [3, 10, 5]
targets: [3, 7, 5]
num messages: 4

 67%|██████▋   | 91/135 [51:53<24:30, 33.42s/it]

preds: [10, 10, 2, 2]
targets: [10, 10, 3, 2]
num messages: 4

 68%|██████▊   | 92/135 [52:31<24:51, 34.69s/it]

preds: [6, 10, 2, 7]
targets: [7, 10, 3, 6]
num messages: 4

 69%|██████▉   | 93/135 [53:04<23:54, 34.17s/it]

preds: [4, 4, 8, 3]
targets: [4, 4, 8, 3]
num messages: 4

 70%|██████▉   | 94/135 [53:48<25:23, 37.15s/it]

preds: [9, 7, 4, 3]
targets: [9, 7, 4, 4]
num messages: 4

 70%|███████   | 95/135 [54:33<26:25, 39.64s/it]

preds: [7, 10, 7, 3]
targets: [8, 10, 7, 3]
num messages: 4

 71%|███████   | 96/135 [55:18<26:48, 41.24s/it]

preds: [2, 2, 8, 3]
targets: [3, 2, 10, 3]
num messages: 4

 72%|███████▏  | 97/135 [56:04<26:53, 42.47s/it]

preds: [10, 12, 9, 4]
targets: [8, 7, 10, 4]
num messages: 4

 73%|███████▎  | 98/135 [56:39<24:52, 40.33s/it]

preds: [7, 3, 4, 2]
targets: [6, 3, 4, 2]
num messages: 4

 73%|███████▎  | 99/135 [57:19<24:04, 40.14s/it]

preds: [2, 8, 8, 5]
targets: [2, 8, 10, 5]
num messages: 4

 74%|███████▍  | 100/135 [58:06<24:40, 42.29s/it]

preds: [3, 5, 2, 3]
targets: [3, 6, 2, 4]
num messages: 4

 75%|███████▍  | 101/135 [58:42<22:50, 40.30s/it]

preds: [5, 8, 2, 6]
targets: [5, 7, 2, 6]
num messages: 4

 76%|███████▌  | 102/135 [59:10<20:13, 36.78s/it]

preds: [7, 9, 3, 2]
targets: [7, 9, 3, 2]
num messages: 4

 76%|███████▋  | 103/135 [59:41<18:40, 35.03s/it]

preds: [7, 2, 3, 7]
targets: [8, 2, 2, 8]
num messages: 4

 77%|███████▋  | 104/135 [1:00:09<16:58, 32.85s/it]

preds: [7, 6, 6, 6]
targets: [8, 6, 6, 6]
request failed: https://live.staticflickr.com/65535/52882230291_4da05b7c32_h.jpg
num messages: 3

 78%|███████▊  | 105/135 [1:00:39<15:59, 31.97s/it]

preds: [9, 4, 7]
targets: [9, 4, 7]
request failed: https://live.staticflickr.com/4913/45977842825_dd69bdb937_h.jpg
num messages: 3

 79%|███████▊  | 106/135 [1:01:02<14:10, 29.34s/it]

preds: [4, 6, 10]
targets: [4, 7, 9]
num messages: 4

 79%|███████▉  | 107/135 [1:01:38<14:34, 31.23s/it]

preds: [2, 6, 2, 6]
targets: [2, 7, 2, 6]
num messages: 4

 80%|████████  | 108/135 [1:02:00<12:51, 28.58s/it]

preds: [6, 3, 5, 5]
targets: [5, 3, 5, 5]
num messages: 4

 81%|████████  | 109/135 [1:02:37<13:28, 31.11s/it]

preds: [4, 9, 6, 2]
targets: [4, 9, 6, 2]
num messages: 4

 81%|████████▏ | 110/135 [1:03:02<12:08, 29.16s/it]

preds: [7, 6, 2, 9]
targets: [7, 6, 2, 8]
num messages: 4

 82%|████████▏ | 111/135 [1:03:32<11:51, 29.65s/it]

preds: [7, 5, 8, 4]
targets: [8, 6, 8, 4]
num messages: 4

 83%|████████▎ | 112/135 [1:04:06<11:46, 30.72s/it]

preds: [2, 5, 4, 2]
targets: [2, 5, 4, 2]
num messages: 4

 84%|████████▎ | 113/135 [1:04:39<11:30, 31.38s/it]

preds: [8, 2, 5, 7]
targets: [8, 2, 6, 9]
num messages: 4

 84%|████████▍ | 114/135 [1:05:03<10:12, 29.17s/it]

preds: [9, 8, 6, 9]
targets: [9, 9, 5, 10]
num messages: 4

 85%|████████▌ | 115/135 [1:05:34<09:56, 29.80s/it]

preds: [8, 5, 3, 10]
targets: [8, 6, 3, 10]
num messages: 4

 86%|████████▌ | 116/135 [1:06:42<13:05, 41.32s/it]

preds: [2, 5, 7, 9]
targets: [3, 5, 7, 8]
num messages: 4

 87%|████████▋ | 117/135 [1:07:25<12:29, 41.66s/it]

preds: [9, 8, 10, 4]
targets: [10, 9, 8, 6]
num messages: 4

 87%|████████▋ | 118/135 [1:08:10<12:06, 42.74s/it]

preds: [6, 10, 10, 6]
targets: [6, 9, 10, 6]
num messages: 4

 88%|████████▊ | 119/135 [1:08:58<11:49, 44.34s/it]

preds: [5, 10, 8, 2]
targets: [5, 9, 8, 2]
num messages: 4

 89%|████████▉ | 120/135 [1:09:36<10:38, 42.57s/it]

preds: [4, 10, 3, 4]
targets: [4, 10, 3, 5]
num messages: 4

 90%|████████▉ | 121/135 [1:09:47<07:43, 33.09s/it]

preds: [2, 3, 2, 8]
targets: [2, 3, 2, 8]
num messages: 4

 90%|█████████ | 122/135 [1:10:33<07:59, 36.90s/it]

preds: [10, 1, 3, 11]
targets: [5, 2, 3, 8]
num messages: 4

 91%|█████████ | 123/135 [1:11:42<09:17, 46.44s/it]

preds: [9, 8, 4, 2]
targets: [10, 8, 4, 2]
num messages: 4

 92%|█████████▏| 124/135 [1:12:30<08:36, 46.97s/it]

preds: [3, 3, 7, 6]
targets: [3, 3, 7, 7]
num messages: 4

 93%|█████████▎| 125/135 [1:13:09<07:26, 44.64s/it]

preds: [9, 6, 2, 4]
targets: [9, 7, 2, 4]
num messages: 4

 93%|█████████▎| 126/135 [1:13:43<06:13, 41.47s/it]

preds: [6, 3, 4, 3]
targets: [7, 3, 4, 3]
num messages: 4

 94%|█████████▍| 127/135 [1:14:06<04:46, 35.85s/it]

preds: [6, 5, 7, 10]
targets: [7, 7, 7, 8]
num messages: 4

 95%|█████████▍| 128/135 [1:14:39<04:05, 35.07s/it]

preds: [5, 4, 12, 4]
targets: [5, 4, 10, 6]
num messages: 4

 96%|█████████▌| 129/135 [1:15:04<03:12, 32.13s/it]

preds: [4, 0, 7, 7]
targets: [4, 4, 7, 8]
num messages: 4

 96%|█████████▋| 130/135 [1:15:45<02:53, 34.68s/it]

preds: [3, 9, 5, 7]
targets: [4, 9, 5, 7]
num messages: 4

 97%|█████████▋| 131/135 [1:16:03<01:59, 29.77s/it]

preds: [6, 9, 8, 2]
targets: [6, 9, 8, 2]
num messages: 4

 98%|█████████▊| 132/135 [1:17:03<01:56, 38.68s/it]

preds: [2, 9, 2, 2]
targets: [2, 9, 2, 2]
num messages: 4

 99%|█████████▊| 133/135 [1:18:15<01:37, 48.64s/it]

preds: [5, 2, 8, 6]
targets: [5, 8, 8, 7]
num messages: 4

 99%|█████████▉| 134/135 [1:18:55<00:46, 46.14s/it]

preds: [4, 4, 2, 4]
targets: [4, 4, 2, 4]
num messages: 4

100%|██████████| 135/135 [1:19:21<00:00, 35.27s/it]

preds: [2, 6, 4, 4]
targets: [2, 8, 4, 4]

Empty DataFrame
Columns: [pred, target]
Index: []

   accuracy  mean_error  mean_squared_error
0  0.628083    0.565465            1.392789

## PCA Analysis

In [ ]:
load_params = {
    'Qwen/Qwen3-VL-2B-Instruct': {
        'dtype': torch.bfloat16,
        'device_map': "auto",
        'attn_implementation': 'eager'
    },

    'llava-hf/llava-1.5-7b-hf': {
        'torch_dtype': torch.float16,
        'low_cpu_mem_usage': True,
        'attn_implementation': 'eager'
    },

    'allenai/Molmo2-8B': {
        'dtype': "auto",
        'device_map': "auto",
        'trust_remote_code': True
    }
}

model = AutoModelForImageTextToText.from_pretrained(
     model_id, **load_params[model_id]
).to('cuda:0')
processor = AutoProcessor.from_pretrained(model_id, trust_remote_code = True)
processor.tokenizer.padding_side = "left"

config.json: 0.00B [00:00, ?B/s]

configuration_molmo2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/allenai/Molmo2-8B:
- configuration_molmo2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

modeling_molmo2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/allenai/Molmo2-8B:
- modeling_molmo2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 8 files:   0%|          | 0/8 [00:00<?, ?it/s]

model-00003-of-00008.safetensors:   0%|          | 0.00/4.63G [00:00<?, ?B/s]

model-00001-of-00008.safetensors:   0%|          | 0.00/4.97G [00:00<?, ?B/s]

model-00004-of-00008.safetensors:   0%|          | 0.00/4.63G [00:00<?, ?B/s]

model-00008-of-00008.safetensors:   0%|          | 0.00/2.49G [00:00<?, ?B/s]

model-00005-of-00008.safetensors:   0%|          | 0.00/4.63G [00:00<?, ?B/s]

model-00002-of-00008.safetensors:   0%|          | 0.00/4.63G [00:00<?, ?B/s]

model-00006-of-00008.safetensors:   0%|          | 0.00/4.63G [00:00<?, ?B/s]

model-00007-of-00008.safetensors:   0%|          | 0.00/4.03G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/117 [00:00<?, ?B/s]

processor_config.json:   0%|          | 0.00/301 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

processing_molmo2.py: 0.00B [00:00, ?B/s]

video_processing_molmo2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/allenai/Molmo2-8B:
- video_processing_molmo2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

image_processing_molmo2.py: 0.00B [00:00, ?B/s]

A new version of the following files was downloaded from https://huggingface.co/allenai/Molmo2-8B:
- image_processing_molmo2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.
A new version of the following files was downloaded from https://huggingface.co/allenai/Molmo2-8B:
- processing_molmo2.py
- video_processing_molmo2.py
- image_processing_molmo2.py
. Make sure to double-check they do not contain any added malicious code. To avoid downloading new versions of the code file, you can pin a revision.

preprocessor_config.json:   0%|          | 0.00/555 [00:00<?, ?B/s]

Using a slow image processor as `use_fast` is unset and a slow processor was saved with this model. `use_fast=True` will be the default behavior in v4.52, even if the model was saved with a slow processor. This will result in minor differences in outputs. You'll still be able to use a slow processor with `use_fast=False`.

video_preprocessor_config.json:   0%|          | 0.00/984 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/11.5M [00:00<?, ?B/s]

added_tokens.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

### Logging

In [ ]:
layers_to_hook = {
    'Qwen/Qwen3-VL-2B-Instruct': [
        'model.visual.blocks.1',                # early visual features extracted by visual encoder
        'model.visual.blocks.11',                # mid visual features extracted by visual encoder
        'model.visual.blocks.23',               # final visual information extracted from image by visual encoder

        'model.visual.merger',                  # visual features 'mapped' to global language space

        'model.visual.deepstack_merger_list.0', # visual features added to corresponding activations during early language reasoning (in the 'language' decoder)
        'model.visual.deepstack_merger_list.1', # visual features added to corresponding activations during early language reasoning (in the 'language' decoder)
        'model.visual.deepstack_merger_list.2', # visual features added to corresponding activations during early language reasoning (in the 'language' decoder)

        'model.language_model.layers.0',
        'model.language_model.layers.1',        # early language features extracted by decoder
        'model.language_model.layers.13',       # mid language features extracted by decoder
        'model.language_model.layers.20',
        'model.language_model.layers.27'       # final language features extracted by decoder
    ],
    'llava-hf/llava-1.5-7b-hf': [
        'model.vision_tower.vision_model.encoder.layers.1',
        'model.vision_tower.vision_model.encoder.layers.11',
        'model.vision_tower.vision_model.encoder.layers.23',

        'model.multi_modal_projector',

        'model.language_model.layers.0',
        'model.language_model.layers.1',
        'model.language_model.layers.15',
        'model.language_model.layers.23',
        'model.language_model.layers.31'
    ],
    'allenai/Molmo2-8B':[
        'model.vision_backbone.image_vit.transformer.resblocks.1',
        'model.vision_backbone.image_vit.transformer.resblocks.12',
        'model.vision_backbone.image_vit.transformer.resblocks.24',

        'model.vision_backbone.image_projector',

        'model.transformer.blocks.0',
        'model.transformer.blocks.1',
        'model.transformer.blocks.17',
        'model.transformer.blocks.26',
        'model.transformer.blocks.35'
    ]
}

attentions_to_grab = {
    'Qwen/Qwen3-VL-2B-Instruct': [
        0, 1, 13, 27
    ],
    'llava-hf/llava-1.5-7b-hf': [
        0, 1, 15, 30, 31
    ],
    'allenai/Molmo2-8B':[
        # eager attention not supported
    ]
}

In [ ]:
# activation cache
activation_cache = {}

# activation data
activation_data = []

# hook for activation logging
def log_activations(module_name):
    def hook(module, inp, out):
        print(f'caught {module_name}')
        x = out[0] if isinstance(out, (tuple, list)) else out
        if torch.is_tensor(x):
            activation_cache[module_name] = (
                x.detach()
                .to(dtype=torch.float32)
                .cpu()
            )
    return hook

# attach hooks
def attach_hooks(model, model_id):
    to_hook = layers_to_hook[model_id]
    for module_name, module in model.named_modules():
        if module_name in to_hook:
            print(f'hooked: {module_name}')
            module.register_forward_hook(log_activations(module_name))

# callback for storing activation data
def store_activations(inputs, targets, preds, hidden_states, attentions):
    print('detaching activations')
    attentions = attentions[0] # assumes single token generated

    input_ids_cpu = inputs["input_ids"].detach().cpu().tolist()
    tokens_batch = [processor.tokenizer.convert_ids_to_tokens(ids) for ids in input_ids_cpu]

    act_cpu = {layer: activation_cache[layer].detach().cpu().numpy() for layer in layers_to_hook[model_id]}

    att_cpu = {lid: attentions[lid].detach().cpu().to(torch.float16).numpy() for lid in attentions_to_grab[model_id]}

    print('detached data, storing')
    for i in range(len(targets)):
        print(f'storing idx {i} in batch')
        activation_data.append({
            'input_tokens': tokens_batch[i],
            'target': targets[i],
            'pred': preds[i]
        })
        for layer in layers_to_hook[model_id]:
            print(f'storing {layer}')
            activation_data[-1][layer] = act_cpu[layer][i]

        if attentions_to_grab[model_id] != []:
            for layer_id in attentions_to_grab[model_id]:
                print(f'storing attention_{layer_id}')
                activation_data[-1][f'attention_{layer_id}'] = att_cpu[layer_id][i].mean(axis=-3)

# clear hooks
def clear_hooks():
    for module_name, module in model.named_modules():
        if module_name in layers_to_hook[model_id]:
            module._forward_hooks.clear()

# reset logs
def reset_logs():
    activation_cache.clear()
    activation_data.clear()
    clear_hooks()

# pca plotting
def layer_pca_plots():
  pass

### Run feedforward

In [ ]:
# function for filtering out rows in pixmo with count > 5

def counts_filter(data: pd.DataFrame):
    return data.iloc[(data['count'].to_numpy() <= 5).tolist()].reset_index(drop=True)

In [ ]:
test_dataset = pixmoDataset(split='test', processor=processor, portion=DATA_PORTION, filter_fn=counts_filter)

print(f'test dataset size: {len(test_dataset)}')
print(test_dataset.data.head(10))

metric_fns = {}

'(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), '(Request ID: 164299ad-58ab-4b6b-b264-1078a3d72ba6)')' thrown while requesting GET https://huggingface.co/datasets/allenai/pixmo-count/resolve/main/data/test-00000-of-00001.parquet
WARNING:huggingface_hub.utils._http:'(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')), '(Request ID: 164299ad-58ab-4b6b-b264-1078a3d72ba6)')' thrown while requesting GET https://huggingface.co/datasets/allenai/pixmo-count/resolve/main/data/test-00000-of-00001.parquet
Retrying in 1s [Retry 1/5].
WARNING:huggingface_hub.utils._http:Retrying in 1s [Retry 1/5].

test dataset size: 240
                                           image_url        label  count
0  https://live.staticflickr.com/65535/5072578687...       people      5
1  https://live.staticflickr.com/3672/9624035497_...       people      4
2  https://live.staticflickr.com/1979/45001822892...       people      5
3  https://live.staticflickr.com/3692/9251404684_...       people      4
4  https://live.staticflickr.com/7509/16135146130...       people      3
5  https://live.staticflickr.com/2278/2077685668_...         dogs      3
6  https://live.staticflickr.com/7427/9935572953_...  helicopters      5
7  https://live.staticflickr.com/7350/27704496056...        ducks      3
8  https://live.staticflickr.com/7076/7168922099_...       people      2
9  https://live.staticflickr.com/2918/14390837392...    airplanes      5

In [ ]:
reset_logs()

evaluator = Evaluator(
    metric_fns=metric_fns,
    batch_size=4,
    shuffle=False,
    collate_fn=pixmo_collate_fn(processor),
    token_allowance=1, # 1 thru 9 represented by uno token,
    callbacks=[store_activations]
)

attach_hooks(model, model_id)

results = evaluator(model, processor, test_dataset, needs_attentions=True)

save_df('activation_data', pd.DataFrame(activation_data), show_df=True)

clear_hooks()

hooked: model.transformer.blocks.0
hooked: model.transformer.blocks.1
hooked: model.transformer.blocks.17
hooked: model.transformer.blocks.26
hooked: model.transformer.blocks.35
hooked: model.vision_backbone.image_vit.transformer.resblocks.1
hooked: model.vision_backbone.image_vit.transformer.resblocks.12
hooked: model.vision_backbone.image_vit.transformer.resblocks.24
hooked: model.vision_backbone.image_projector

  0%|          | 0/60 [00:00<?, ?it/s]

num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

  2%|▏         | 1/60 [00:06<06:04,  6.17s/it]

preds: [5, 4, 5, 4]
targets: [5, 4, 5, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

  3%|▎         | 2/60 [00:12<06:02,  6.25s/it]

preds: [3, 2, 5, 3]
targets: [3, 3, 5, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
request failed: https://live.staticflickr.com/7076/7168922099_cbb6717c58_h.jpg
num messages: 3
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

  5%|▌         | 3/60 [00:17<05:20,  5.62s/it]

preds: [5, 3, 3]
targets: [5, 3, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

  7%|▋         | 4/60 [00:23<05:27,  5.85s/it]

preds: [3, 5, 3, 4]
targets: [3, 5, 3, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

  8%|▊         | 5/60 [00:29<05:28,  5.97s/it]

preds: [3, 5, 4, 5]
targets: [3, 5, 4, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 10%|█         | 6/60 [00:35<05:26,  6.04s/it]

preds: [5, 2, 6, 3]
targets: [5, 2, 5, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 12%|█▏        | 7/60 [00:42<05:22,  6.08s/it]

preds: [4, 4, 2, 2]
targets: [4, 4, 2, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 13%|█▎        | 8/60 [00:48<05:17,  6.10s/it]

preds: [2, 2, 4, 4]
targets: [2, 2, 5, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 15%|█▌        | 9/60 [00:54<05:14,  6.17s/it]

preds: [4, 2, 5, 2]
targets: [4, 2, 5, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 17%|█▋        | 10/60 [01:00<05:09,  6.19s/it]

preds: [2, 5, 4, 5]
targets: [2, 5, 4, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 18%|█▊        | 11/60 [01:06<05:03,  6.19s/it]

preds: [3, 4, 4, 0]
targets: [3, 4, 4, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 20%|██        | 12/60 [01:13<04:56,  6.17s/it]

preds: [2, 4, 2, 3]
targets: [2, 5, 2, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 22%|██▏       | 13/60 [01:19<04:49,  6.16s/it]

preds: [4, 5, 6, 4]
targets: [4, 5, 5, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 23%|██▎       | 14/60 [01:25<04:42,  6.14s/it]

preds: [3, 5, 5, 5]
targets: [3, 5, 5, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 25%|██▌       | 15/60 [01:31<04:36,  6.15s/it]

preds: [3, 2, 4, 3]
targets: [3, 2, 4, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 27%|██▋       | 16/60 [01:37<04:31,  6.17s/it]

preds: [3, 3, 5, 5]
targets: [3, 3, 5, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 28%|██▊       | 17/60 [01:43<04:26,  6.19s/it]

preds: [4, 4, 3, 2]
targets: [5, 4, 3, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 30%|███       | 18/60 [01:50<04:20,  6.20s/it]

preds: [4, 3, 5, 4]
targets: [4, 3, 4, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 32%|███▏      | 19/60 [01:56<04:14,  6.20s/it]

preds: [3, 2, 3, 2]
targets: [3, 2, 3, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 33%|███▎      | 20/60 [02:02<04:06,  6.16s/it]

preds: [2, 3, 4, 4]
targets: [2, 3, 4, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 35%|███▌      | 21/60 [02:08<04:01,  6.18s/it]

preds: [5, 3, 5, 4]
targets: [5, 3, 5, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 37%|███▋      | 22/60 [02:13<03:42,  5.86s/it]

preds: [3, 2, 5, 4]
targets: [3, 2, 5, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 38%|███▊      | 23/60 [02:20<03:42,  6.01s/it]

preds: [5, 4, 3, 4]
targets: [5, 4, 4, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 40%|████      | 24/60 [02:26<03:37,  6.05s/it]

preds: [4, 2, 4, 3]
targets: [5, 2, 4, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 42%|████▏     | 25/60 [02:32<03:32,  6.07s/it]

preds: [3, 2, 4, 2]
targets: [3, 2, 4, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 43%|████▎     | 26/60 [02:38<03:26,  6.08s/it]

preds: [5, 2, 5, 3]
targets: [5, 2, 5, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 45%|████▌     | 27/60 [02:44<03:21,  6.09s/it]

preds: [5, 3, 5, 2]
targets: [5, 3, 5, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 47%|████▋     | 28/60 [02:50<03:16,  6.13s/it]

preds: [2, 6, 2, 4]
targets: [2, 4, 2, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 48%|████▊     | 29/60 [02:57<03:11,  6.16s/it]

preds: [2, 5, 2, 3]
targets: [2, 5, 2, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 50%|█████     | 30/60 [03:03<03:04,  6.16s/it]

preds: [4, 5, 3, 2]
targets: [4, 5, 4, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 52%|█████▏    | 31/60 [03:09<02:59,  6.19s/it]

preds: [3, 4, 3, 2]
targets: [3, 4, 3, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 53%|█████▎    | 32/60 [03:15<02:52,  6.18s/it]

preds: [4, 3, 5, 4]
targets: [4, 3, 5, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 55%|█████▌    | 33/60 [03:21<02:46,  6.17s/it]

preds: [5, 4, 3, 2]
targets: [5, 4, 3, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 57%|█████▋    | 34/60 [03:27<02:40,  6.17s/it]

preds: [5, 3, 2, 5]
targets: [5, 3, 3, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 58%|█████▊    | 35/60 [03:34<02:35,  6.21s/it]

preds: [1, 4, 5, 5]
targets: [4, 4, 5, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 60%|██████    | 36/60 [03:40<02:29,  6.22s/it]

preds: [2, 6, 3, 2]
targets: [3, 5, 3, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 62%|██████▏   | 37/60 [03:46<02:23,  6.25s/it]

preds: [5, 3, 5, 5]
targets: [5, 3, 5, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 63%|██████▎   | 38/60 [03:53<02:17,  6.26s/it]

preds: [3, 2, 3, 2]
targets: [3, 2, 3, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 65%|██████▌   | 39/60 [03:59<02:11,  6.25s/it]

preds: [3, 5, 2, 2]
targets: [3, 5, 3, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 67%|██████▋   | 40/60 [04:05<02:04,  6.22s/it]

preds: [2, 4, 4, 3]
targets: [3, 4, 4, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 68%|██████▊   | 41/60 [04:11<01:57,  6.19s/it]

preds: [4, 4, 3, 3]
targets: [4, 4, 3, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 70%|███████   | 42/60 [04:17<01:51,  6.19s/it]

preds: [2, 3, 4, 3]
targets: [2, 3, 4, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 72%|███████▏  | 43/60 [04:24<01:45,  6.19s/it]

preds: [4, 2, 2, 5]
targets: [4, 2, 2, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 73%|███████▎  | 44/60 [04:30<01:39,  6.23s/it]

preds: [3, 2, 4, 5]
targets: [3, 2, 4, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 75%|███████▌  | 45/60 [04:36<01:33,  6.22s/it]

preds: [2, 3, 2, 2]
targets: [2, 3, 2, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 77%|███████▋  | 46/60 [04:42<01:26,  6.21s/it]

preds: [3, 4, 4, 2]
targets: [2, 4, 4, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 78%|███████▊  | 47/60 [04:48<01:20,  6.19s/it]

preds: [2, 5, 3, 5]
targets: [2, 5, 3, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 80%|████████  | 48/60 [04:55<01:14,  6.19s/it]

preds: [5, 4, 2, 2]
targets: [5, 4, 2, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 82%|████████▏ | 49/60 [05:00<01:05,  5.96s/it]

preds: [4, 2, 5, 4]
targets: [4, 2, 5, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 83%|████████▎ | 50/60 [05:06<01:00,  6.04s/it]

preds: [2, 2, 5, 3]
targets: [2, 2, 5, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 85%|████████▌ | 51/60 [05:12<00:55,  6.12s/it]

preds: [3, 5, 5, 2]
targets: [3, 5, 5, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 87%|████████▋ | 52/60 [05:19<00:49,  6.13s/it]

preds: [4, 3, 5, 2]
targets: [4, 3, 5, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 88%|████████▊ | 53/60 [05:24<00:40,  5.81s/it]

preds: [3, 2, 6, 1]
targets: [3, 2, 5, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 90%|█████████ | 54/60 [05:30<00:35,  5.92s/it]

preds: [3, 4, 2, 3]
targets: [3, 4, 2, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 92%|█████████▏| 55/60 [05:36<00:29,  5.99s/it]

preds: [3, 2, 4, 3]
targets: [3, 2, 4, 3]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 93%|█████████▎| 56/60 [05:42<00:24,  6.04s/it]

preds: [4, 3, 5, 4]
targets: [4, 3, 5, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 95%|█████████▌| 57/60 [05:49<00:18,  6.12s/it]

preds: [4, 4, 4, 5]
targets: [4, 4, 4, 5]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 97%|█████████▋| 58/60 [05:55<00:12,  6.11s/it]

preds: [2, 2, 2, 2]
targets: [2, 2, 2, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

 98%|█████████▊| 59/60 [06:01<00:06,  6.13s/it]

preds: [5, 4, 4, 2]
targets: [5, 4, 4, 2]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
num messages: 4
caught model.vision_backbone.image_vit.transformer.resblocks.1
caught model.vision_backbone.image_vit.transformer.resblocks.12
caught model.vision_backbone.image_vit.transformer.resblocks.24
caught model.vision_backbone.image_projector
caught model.transformer.blocks.0
caught model.transformer.blocks.1
caught model.transformer.blocks.17
caught model.transformer.blocks.26
caught model.transformer.blocks.35

100%|██████████| 60/60 [06:07<00:00,  6.13s/it]

preds: [4, 2, 4, 4]
targets: [4, 2, 4, 4]
detaching activations
detached data, storing
storing idx 0 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 1 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 2 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35
storing idx 3 in batch
storing model.vision_backbone.image_vit.transformer.resblocks.1
storing model.vision_backbone.image_vit.transformer.resblocks.12
storing model.vision_backbone.image_vit.transformer.resblocks.24
storing model.vision_backbone.image_projector
storing model.transformer.blocks.0
storing model.transformer.blocks.1
storing model.transformer.blocks.17
storing model.transformer.blocks.26
storing model.transformer.blocks.35

,input_tokens,target,pred,model.vision_backbone.image_vit.transformer.resblocks.1,model.vision_backbone.image_vit.transformer.resblocks.12,model.vision_backbone.image_vit.transformer.resblocks.24,model.vision_backbone.image_projector,model.transformer.blocks.0,model.transformer.blocks.1,model.transformer.blocks.17,model.transformer.blocks.26,model.transformer.blocks.35
0,"[<|im_end|>, <low_res_im_start>, <im_patch>, <...",5,5,"[[0.09089747, 0.094417684, 0.0795076, -0.14841...","[[-0.05144971, -0.056074128, 0.038487792, -0.1...","[[-0.8997775, 0.9769423, -0.298482, 0.48140284...","[[-1.2173767, 0.5716996, 0.42625633, -0.320909...","[[-0.051880065, 0.042939056, -0.03975417, -0.3...","[[-0.10301135, 0.109460935, -0.06389668, -0.32...","[[3.7860124, 3.9851258, -2.5295005, -9.458545,...","[[1.6375004, 3.9255838, -3.1217768, -8.817377,...","[[109.70213, 5.5074663, 133.76143, -47.16627, ..."
1,"[<|endoftext|>, <|endoftext|>, <|endoftext|>, ...",4,4,"[[-0.00074416026, 0.16850665, -0.009863712, -0...","[[-0.16084145, -0.16606763, -0.18470135, 0.089...","[[-0.18915856, 0.08319497, -0.5412944, 0.10525...","[[-0.67370325, 0.27498043, 2.6290443, 1.806113...","[[0.42189744, 0.097749785, 1.0772955, 0.131759...","[[0.6224927, 0.063491434, 1.0132124, 0.1249691...","[[-0.22283438, 0.72549707, -1.1144251, 0.23154...","[[-2.2662284, -1.9191232, 1.6694223, 0.4329958...","[[11.907283, -1.8353949, 12.850586, -12.401773..."
2,"[<|im_end|>, <low_res_im_start>, <im_patch>, <...",5,5,"[[0.014729757, 0.051083386, 0.08793838, -0.084...","[[-0.043284364, -0.06413045, -0.08127661, -0.0...","[[-0.9932815, -0.1285617, -0.30303812, 0.60863...","[[-0.5621706, 0.5748884, -0.025511047, -0.8323...","[[-0.051880065, 0.042939056, -0.03975417, -0.3...","[[-0.10301135, 0.109460935, -0.06389668, -0.32...","[[3.7860124, 3.9851258, -2.5295005, -9.458545,...","[[1.6375004, 3.9255838, -3.1217768, -8.817377,...","[[109.70213, 5.5074663, 133.76143, -47.16627, ..."
3,"[<|im_end|>, <low_res_im_start>, <im_patch>, <...",4,4,"[[0.01979322, 0.046457022, 0.048576266, -0.158...","[[0.3621316, 0.0018665642, -0.68047124, 0.2807...","[[0.36855394, 0.1423938, -0.99600714, 0.865866...","[[-0.7992014, 0.88124514, -1.5055662, -0.34945...","[[-0.051880065, 0.042939056, -0.03975417, -0.3...","[[-0.10301135, 0.109460935, -0.06389668, -0.32...","[[3.7860124, 3.9851258, -2.5295005, -9.458545,...","[[1.6375004, 3.9255838, -3.1217768, -8.817377,...","[[109.70213, 5.5074663, 133.76143, -47.16627, ..."
4,"[<|endoftext|>, <|endoftext|>, <|endoftext|>, ...",3,3,"[[0.11112512, -0.08760736, 0.2911582, -0.14200...","[[0.48816156, -0.2540673, 0.19036978, -0.02865...","[[-1.0807502, 0.099523306, -0.14507145, 0.1875...","[[-0.83966154, 0.020146454, 0.6133335, -0.3820...","[[0.42189744, 0.097749785, 1.0772955, 0.131759...","[[0.6224927, 0.063491434, 1.0132124, 0.1249691...","[[-0.22283438, 0.72549707, -1.1144251, 0.23154...","[[-2.2662284, -1.9191232, 1.6694223, 0.4329958...","[[11.907283, -1.8353949, 12.850586, -12.401773..."
...,...,...,...,...,...,...,...,...,...,...,...,...
234,"[<|im_end|>, <low_res_im_start>, <im_patch>, <...",2,2,"[[0.17610297, 0.336736, 0.33519712, -0.1280908...","[[-0.12851481, 0.111093655, 0.12337954, 0.2932...","[[0.090909004, -0.18073854, -0.03732586, 0.952...","[[-0.89622533, -0.07364055, 0.14212687, 0.9931...","[[-0.051880065, 0.042939056, -0.03975417, -0.3...","[[-0.10301135, 0.109460935, -0.06389668, -0.32...","[[3.7860124, 3.9851258, -2.5295005, -9.458545,...","[[1.6375004, 3.9255838, -3.1217768, -8.817377,...","[[109.70213, 5.5074663, 133.76143, -47.16627, ..."
235,"[<|endoftext|>, <|endoftext|>, <|endoftext|>, ...",4,4,"[[-0.011503331, 0.049438305, 0.08440389, -0.07...","[[-0.011396177, -0.14299646, 0.2644027, -0.060...","[[0.048731804, 0.17382777, 0.32908922, 0.50340...","[[-0.7176744, -1.0352402, -0.72593063, -0.9346...","[[0.42189744, 0.097749785, 1.0772955, 0.131759...","[[0.6224927, 0.063491434, 1.0132124, 0.1249691...","[[-0.22283438, 0.72549707, -1.1144251, 0.23154...","[[-2.2662284, -1.9191232, 1.6694223, 0.4329958...","[[11.907283, -1.8353949, 12.850586, -12.401773..."
236,"[<|im_end|>, <low_res_im_start>, <im_patch>, <...",2,2,"[[0.033033542, 0.043881193, 0.04097271, -0.079...","[[-0.0639431, -0.1664465, 0.22162896, 0.098757...","[[-0.43944418, -0.30851257, 0.7178697, 0.39877...","[[-0.5034425, 1.0542985, -0.278022, -0.7420025...","[[-0.051880065, 0.042939056, -0.03975417, -0.3...","[[-0.10301135, 0.109460935, -0.06389668, -0.32...","[[3.7860124, 3.9851258, -2.5295005, -9.458545,...","[[1.6375004, 3.9255838, -3.1217768, -8.817377,...","[[109.70213, 5.5074663, 133.76143, -47.16627, ..."
237,"[<|endoftext|>, <|endoftext|>, <|endoftext|>, ...",4,4,"[[0.061831955, 0.09116437, 0.08322971, -0.0174...","[[0.00043427944, -0.06440435, -0.09229685, -0....","[[-0.36967182, -0.3298542, 0.107426584, 0.0280...","[[-0.20454796, -0.08458876, -0.29182613, -1.43...","[[0.42189744, 0.097749785, 1.0772955, 0.131759...","[[0.6224927, 0.063491434, 1.0132124, 0.1249691...","[[-0.22283438, 0.72549707, -1.1144251, 0.23154...","[[-2.2662284, -1.9191232, 1.6694223, 0.4329958...","[[11.907283, -1.8353949, 12.850586, -12.401773..."
238,"[<|endoftext|>, <|endoftext|>, <|endoftext|>, ...",4,4,"[[-0.048140615, -0.012419477, 0.037271768, -0....","[[-0.1507582, -0.08383445, 0.20326573, -0.0315...","[[-0.41779208, -0.46916246, 0.7377519, 0.64319...","[[0.2120346, -0.087521486, 0.32379165, -0.3387...","[[0.42189744, 0.097749785, 1.0772955, 0.131759...","[[0.6224927, 0.063491434, 1.0132124, 0.1249691...","[[-0.22283438, 0.72549707, -1.1144251, 0.23154...","[[-2.2662284, -1.9191232, 1.6694223, 0.4329958...","[[11.907283, -1.8353949, 12.850586, -12.401773..."

In [ ]:
pd.DataFrame(activation_data).head()

In [ ]:

print('a')
load_df('activation_data')['attention_1'][0]

In [ ]:
activation_data[0]['attention_1'].shape

In [ ]:
#show
plt.imshow(activation_data[0]['attention_1'], vmin=0, vmax=0.01)

In [ ]:
for name, module in model.model.transformer.blocks[0].self_attn.k_norm.named_modules():
    print(name)

In [ ]:
print(len([name for name, module in model.named_modules()]))

819

In [ ]:
for name, module in model.named_modules():
  print(name)

model
model.transformer
model.transformer.wte
model.transformer.emb_drop
model.transformer.blocks
model.transformer.blocks.0
model.transformer.blocks.0.self_attn
model.transformer.blocks.0.self_attn.att_proj
model.transformer.blocks.0.self_attn.k_norm
model.transformer.blocks.0.self_attn.q_norm
model.transformer.blocks.0.self_attn.attn_out
model.transformer.blocks.0.attn_norm
model.transformer.blocks.0.dropout
model.transformer.blocks.0.mlp
model.transformer.blocks.0.mlp.ff_proj
model.transformer.blocks.0.mlp.ff_out
model.transformer.blocks.0.mlp.act
model.transformer.blocks.0.ff_norm
model.transformer.blocks.1
model.transformer.blocks.1.self_attn
model.transformer.blocks.1.self_attn.att_proj
model.transformer.blocks.1.self_attn.k_norm
model.transformer.blocks.1.self_attn.q_norm
model.transformer.blocks.1.self_attn.attn_out
model.transformer.blocks.1.attn_norm
model.transformer.blocks.1.dropout
model.transformer.blocks.1.mlp
model.transformer.blocks.1.mlp.ff_proj
model.transformer.blocks.1.mlp.ff_out
model.transformer.blocks.1.mlp.act
model.transformer.blocks.1.ff_norm
model.transformer.blocks.2
model.transformer.blocks.2.self_attn
model.transformer.blocks.2.self_attn.att_proj
model.transformer.blocks.2.self_attn.k_norm
model.transformer.blocks.2.self_attn.q_norm
model.transformer.blocks.2.self_attn.attn_out
model.transformer.blocks.2.attn_norm
model.transformer.blocks.2.dropout
model.transformer.blocks.2.mlp
model.transformer.blocks.2.mlp.ff_proj
model.transformer.blocks.2.mlp.ff_out
model.transformer.blocks.2.mlp.act
model.transformer.blocks.2.ff_norm
model.transformer.blocks.3
model.transformer.blocks.3.self_attn
model.transformer.blocks.3.self_attn.att_proj
model.transformer.blocks.3.self_attn.k_norm
model.transformer.blocks.3.self_attn.q_norm
model.transformer.blocks.3.self_attn.attn_out
model.transformer.blocks.3.attn_norm
model.transformer.blocks.3.dropout
model.transformer.blocks.3.mlp
model.transformer.blocks.3.mlp.ff_proj
model.transformer.blocks.3.mlp.ff_out
model.transformer.blocks.3.mlp.act
model.transformer.blocks.3.ff_norm
model.transformer.blocks.4
model.transformer.blocks.4.self_attn
model.transformer.blocks.4.self_attn.att_proj
model.transformer.blocks.4.self_attn.k_norm
model.transformer.blocks.4.self_attn.q_norm
model.transformer.blocks.4.self_attn.attn_out
model.transformer.blocks.4.attn_norm
model.transformer.blocks.4.dropout
model.transformer.blocks.4.mlp
model.transformer.blocks.4.mlp.ff_proj
model.transformer.blocks.4.mlp.ff_out
model.transformer.blocks.4.mlp.act
model.transformer.blocks.4.ff_norm
model.transformer.blocks.5
model.transformer.blocks.5.self_attn
model.transformer.blocks.5.self_attn.att_proj
model.transformer.blocks.5.self_attn.k_norm
model.transformer.blocks.5.self_attn.q_norm
model.transformer.blocks.5.self_attn.attn_out
model.transformer.blocks.5.attn_norm
model.transformer.blocks.5.dropout
model.transformer.blocks.5.mlp
model.transformer.blocks.5.mlp.ff_proj
model.transformer.blocks.5.mlp.ff_out
model.transformer.blocks.5.mlp.act
model.transformer.blocks.5.ff_norm
model.transformer.blocks.6
model.transformer.blocks.6.self_attn
model.transformer.blocks.6.self_attn.att_proj
model.transformer.blocks.6.self_attn.k_norm
model.transformer.blocks.6.self_attn.q_norm
model.transformer.blocks.6.self_attn.attn_out
model.transformer.blocks.6.attn_norm
model.transformer.blocks.6.dropout
model.transformer.blocks.6.mlp
model.transformer.blocks.6.mlp.ff_proj
model.transformer.blocks.6.mlp.ff_out
model.transformer.blocks.6.mlp.act
model.transformer.blocks.6.ff_norm
model.transformer.blocks.7
model.transformer.blocks.7.self_attn
model.transformer.blocks.7.self_attn.att_proj
model.transformer.blocks.7.self_attn.k_norm
model.transformer.blocks.7.self_attn.q_norm
model.transformer.blocks.7.self_attn.attn_out
model.transformer.blocks.7.attn_norm
model.transformer.blocks.7.dropout
model.transformer.blocks.7.mlp
model.transformer.blocks.7.mlp.ff_proj
model.transformer.blocks.7.mlp.ff_out
model.transformer.blocks.7.mlp.act
model.transformer.blocks.7.ff_norm
model.transformer.blocks.8
model.transformer.blocks.8.self_attn
model.transformer.blocks.8.self_attn.att_proj
model.transformer.blocks.8.self_attn.k_norm
model.transformer.blocks.8.self_attn.q_norm
model.transformer.blocks.8.self_attn.attn_out
model.transformer.blocks.8.attn_norm
model.transformer.blocks.8.dropout
model.transformer.blocks.8.mlp
model.transformer.blocks.8.mlp.ff_proj
model.transformer.blocks.8.mlp.ff_out
model.transformer.blocks.8.mlp.act
model.transformer.blocks.8.ff_norm
model.transformer.blocks.9
model.transformer.blocks.9.self_attn
model.transformer.blocks.9.self_attn.att_proj
model.transformer.blocks.9.self_attn.k_norm
model.transformer.blocks.9.self_attn.q_norm
model.transformer.blocks.9.self_attn.attn_out
model.transformer.blocks.9.attn_norm
model.transformer.blocks.9.dropout
model.transformer.blocks.9.mlp
model.transformer.blocks.9.mlp.ff_proj
model.transformer.blocks.9.mlp.ff_out
model.transformer.blocks.9.mlp.act
model.transformer.blocks.9.ff_norm
model.transformer.blocks.10
model.transformer.blocks.10.self_attn
model.transformer.blocks.10.self_attn.att_proj
model.transformer.blocks.10.self_attn.k_norm
model.transformer.blocks.10.self_attn.q_norm
model.transformer.blocks.10.self_attn.attn_out
model.transformer.blocks.10.attn_norm
model.transformer.blocks.10.dropout
model.transformer.blocks.10.mlp
model.transformer.blocks.10.mlp.ff_proj
model.transformer.blocks.10.mlp.ff_out
model.transformer.blocks.10.mlp.act
model.transformer.blocks.10.ff_norm
model.transformer.blocks.11
model.transformer.blocks.11.self_attn
model.transformer.blocks.11.self_attn.att_proj
model.transformer.blocks.11.self_attn.k_norm
model.transformer.blocks.11.self_attn.q_norm
model.transformer.blocks.11.self_attn.attn_out
model.transformer.blocks.11.attn_norm
model.transformer.blocks.11.dropout
model.transformer.blocks.11.mlp
model.transformer.blocks.11.mlp.ff_proj
model.transformer.blocks.11.mlp.ff_out
model.transformer.blocks.11.mlp.act
model.transformer.blocks.11.ff_norm
model.transformer.blocks.12
model.transformer.blocks.12.self_attn
model.transformer.blocks.12.self_attn.att_proj
model.transformer.blocks.12.self_attn.k_norm
model.transformer.blocks.12.self_attn.q_norm
model.transformer.blocks.12.self_attn.attn_out
model.transformer.blocks.12.attn_norm
model.transformer.blocks.12.dropout
model.transformer.blocks.12.mlp
model.transformer.blocks.12.mlp.ff_proj
model.transformer.blocks.12.mlp.ff_out
model.transformer.blocks.12.mlp.act
model.transformer.blocks.12.ff_norm
model.transformer.blocks.13
model.transformer.blocks.13.self_attn
model.transformer.blocks.13.self_attn.att_proj
model.transformer.blocks.13.self_attn.k_norm
model.transformer.blocks.13.self_attn.q_norm
model.transformer.blocks.13.self_attn.attn_out
model.transformer.blocks.13.attn_norm
model.transformer.blocks.13.dropout
model.transformer.blocks.13.mlp
model.transformer.blocks.13.mlp.ff_proj
model.transformer.blocks.13.mlp.ff_out
model.transformer.blocks.13.mlp.act
model.transformer.blocks.13.ff_norm
model.transformer.blocks.14
model.transformer.blocks.14.self_attn
model.transformer.blocks.14.self_attn.att_proj
model.transformer.blocks.14.self_attn.k_norm
model.transformer.blocks.14.self_attn.q_norm
model.transformer.blocks.14.self_attn.attn_out
model.transformer.blocks.14.attn_norm
model.transformer.blocks.14.dropout
model.transformer.blocks.14.mlp
model.transformer.blocks.14.mlp.ff_proj
model.transformer.blocks.14.mlp.ff_out
model.transformer.blocks.14.mlp.act
model.transformer.blocks.14.ff_norm
model.transformer.blocks.15
model.transformer.blocks.15.self_attn
model.transformer.blocks.15.self_attn.att_proj
model.transformer.blocks.15.self_attn.k_norm
model.transformer.blocks.15.self_attn.q_norm
model.transformer.blocks.15.self_attn.attn_out
model.transformer.blocks.15.attn_norm
model.transformer.blocks.15.dropout
model.transformer.blocks.15.mlp
model.transformer.blocks.15.mlp.ff_proj
model.transformer.blocks.15.mlp.ff_out
model.transformer.blocks.15.mlp.act
model.transformer.blocks.15.ff_norm
model.transformer.blocks.16
model.transformer.blocks.16.self_attn
model.transformer.blocks.16.self_attn.att_proj
model.transformer.blocks.16.self_attn.k_norm
model.transformer.blocks.16.self_attn.q_norm
model.transformer.blocks.16.self_attn.attn_out
model.transformer.blocks.16.attn_norm
model.transformer.blocks.16.dropout
model.transformer.blocks.16.mlp
model.transformer.blocks.16.mlp.ff_proj
model.transformer.blocks.16.mlp.ff_out
model.transformer.blocks.16.mlp.act
model.transformer.blocks.16.ff_norm
model.transformer.blocks.17
model.transformer.blocks.17.self_attn
model.transformer.blocks.17.self_attn.att_proj
model.transformer.blocks.17.self_attn.k_norm
model.transformer.blocks.17.self_attn.q_norm
model.transformer.blocks.17.self_attn.attn_out
model.transformer.blocks.17.attn_norm
model.transformer.blocks.17.dropout
model.transformer.blocks.17.mlp
model.transformer.blocks.17.mlp.ff_proj
model.transformer.blocks.17.mlp.ff_out
model.transformer.blocks.17.mlp.act
model.transformer.blocks.17.ff_norm
model.transformer.blocks.18
model.transformer.blocks.18.self_attn
model.transformer.blocks.18.self_attn.att_proj
model.transformer.blocks.18.self_attn.k_norm
model.transformer.blocks.18.self_attn.q_norm
model.transformer.blocks.18.self_attn.attn_out
model.transformer.blocks.18.attn_norm
model.transformer.blocks.18.dropout
model.transformer.blocks.18.mlp
model.transformer.blocks.18.mlp.ff_proj
model.transformer.blocks.18.mlp.ff_out
model.transformer.blocks.18.mlp.act
model.transformer.blocks.18.ff_norm
model.transformer.blocks.19
model.transformer.blocks.19.self_attn
model.transformer.blocks.19.self_attn.att_proj
model.transformer.blocks.19.self_attn.k_norm
model.transformer.blocks.19.self_attn.q_norm
model.transformer.blocks.19.self_attn.attn_out
model.transformer.blocks.19.attn_norm
model.transformer.blocks.19.dropout
model.transformer.blocks.19.mlp
model.transformer.blocks.19.mlp.ff_proj
model.transformer.blocks.19.mlp.ff_out
model.transformer.blocks.19.mlp.act
model.transformer.blocks.19.ff_norm
model.transformer.blocks.20
model.transformer.blocks.20.self_attn
model.transformer.blocks.20.self_attn.att_proj
model.transformer.blocks.20.self_attn.k_norm
model.transformer.blocks.20.self_attn.q_norm
model.transformer.blocks.20.self_attn.attn_out
model.transformer.blocks.20.attn_norm
model.transformer.blocks.20.dropout
model.transformer.blocks.20.mlp
model.transformer.blocks.20.mlp.ff_proj
model.transformer.blocks.20.mlp.ff_out
model.transformer.blocks.20.mlp.act
model.transformer.blocks.20.ff_norm
model.transformer.blocks.21
model.transformer.blocks.21.self_attn
model.transformer.blocks.21.self_attn.att_proj
model.transformer.blocks.21.self_attn.k_norm
model.transformer.blocks.21.self_attn.q_norm
model.transformer.blocks.21.self_attn.attn_out
model.transformer.blocks.21.attn_norm
model.transformer.blocks.21.dropout
model.transformer.blocks.21.mlp
model.transformer.blocks.21.mlp.ff_proj
model.transformer.blocks.21.mlp.ff_out
model.transformer.blocks.21.mlp.act
model.transformer.blocks.21.ff_norm
model.transformer.blocks.22
model.transformer.blocks.22.self_attn
model.transformer.blocks.22.self_attn.att_proj
model.transformer.blocks.22.self_attn.k_norm
model.transformer.blocks.22.self_attn.q_norm
model.transformer.blocks.22.self_attn.attn_out
model.transformer.blocks.22.attn_norm
model.transformer.blocks.22.dropout
model.transformer.blocks.22.mlp
model.transformer.blocks.22.mlp.ff_proj
model.transformer.blocks.22.mlp.ff_out
model.transformer.blocks.22.mlp.act
model.transformer.blocks.22.ff_norm
model.transformer.blocks.23
model.transformer.blocks.23.self_attn
model.transformer.blocks.23.self_attn.att_proj
model.transformer.blocks.23.self_attn.k_norm
model.transformer.blocks.23.self_attn.q_norm
model.transformer.blocks.23.self_attn.attn_out
model.transformer.blocks.23.attn_norm
model.transformer.blocks.23.dropout
model.transformer.blocks.23.mlp
model.transformer.blocks.23.mlp.ff_proj
model.transformer.blocks.23.mlp.ff_out
model.transformer.blocks.23.mlp.act
model.transformer.blocks.23.ff_norm
model.transformer.blocks.24
model.transformer.blocks.24.self_attn
model.transformer.blocks.24.self_attn.att_proj
model.transformer.blocks.24.self_attn.k_norm
model.transformer.blocks.24.self_attn.q_norm
model.transformer.blocks.24.self_attn.attn_out
model.transformer.blocks.24.attn_norm
model.transformer.blocks.24.dropout
model.transformer.blocks.24.mlp
model.transformer.blocks.24.mlp.ff_proj
model.transformer.blocks.24.mlp.ff_out
model.transformer.blocks.24.mlp.act
model.transformer.blocks.24.ff_norm
model.transformer.blocks.25
model.transformer.blocks.25.self_attn
model.transformer.blocks.25.self_attn.att_proj
model.transformer.blocks.25.self_attn.k_norm
model.transformer.blocks.25.self_attn.q_norm
model.transformer.blocks.25.self_attn.attn_out
model.transformer.blocks.25.attn_norm
model.transformer.blocks.25.dropout
model.transformer.blocks.25.mlp
model.transformer.blocks.25.mlp.ff_proj
model.transformer.blocks.25.mlp.ff_out
model.transformer.blocks.25.mlp.act
model.transformer.blocks.25.ff_norm
model.transformer.blocks.26
model.transformer.blocks.26.self_attn
model.transformer.blocks.26.self_attn.att_proj
model.transformer.blocks.26.self_attn.k_norm
model.transformer.blocks.26.self_attn.q_norm
model.transformer.blocks.26.self_attn.attn_out
model.transformer.blocks.26.attn_norm
model.transformer.blocks.26.dropout
model.transformer.blocks.26.mlp
model.transformer.blocks.26.mlp.ff_proj
model.transformer.blocks.26.mlp.ff_out
model.transformer.blocks.26.mlp.act
model.transformer.blocks.26.ff_norm
model.transformer.blocks.27
model.transformer.blocks.27.self_attn
model.transformer.blocks.27.self_attn.att_proj
model.transformer.blocks.27.self_attn.k_norm
model.transformer.blocks.27.self_attn.q_norm
model.transformer.blocks.27.self_attn.attn_out
model.transformer.blocks.27.attn_norm
model.transformer.blocks.27.dropout
model.transformer.blocks.27.mlp
model.transformer.blocks.27.mlp.ff_proj
model.transformer.blocks.27.mlp.ff_out
model.transformer.blocks.27.mlp.act
model.transformer.blocks.27.ff_norm
model.transformer.blocks.28
model.transformer.blocks.28.self_attn
model.transformer.blocks.28.self_attn.att_proj
model.transformer.blocks.28.self_attn.k_norm
model.transformer.blocks.28.self_attn.q_norm
model.transformer.blocks.28.self_attn.attn_out
model.transformer.blocks.28.attn_norm
model.transformer.blocks.28.dropout
model.transformer.blocks.28.mlp
model.transformer.blocks.28.mlp.ff_proj
model.transformer.blocks.28.mlp.ff_out
model.transformer.blocks.28.mlp.act
model.transformer.blocks.28.ff_norm
model.transformer.blocks.29
model.transformer.blocks.29.self_attn
model.transformer.blocks.29.self_attn.att_proj
model.transformer.blocks.29.self_attn.k_norm
model.transformer.blocks.29.self_attn.q_norm
model.transformer.blocks.29.self_attn.attn_out
model.transformer.blocks.29.attn_norm
model.transformer.blocks.29.dropout
model.transformer.blocks.29.mlp
model.transformer.blocks.29.mlp.ff_proj
model.transformer.blocks.29.mlp.ff_out
model.transformer.blocks.29.mlp.act
model.transformer.blocks.29.ff_norm
model.transformer.blocks.30
model.transformer.blocks.30.self_attn
model.transformer.blocks.30.self_attn.att_proj
model.transformer.blocks.30.self_attn.k_norm
model.transformer.blocks.30.self_attn.q_norm
model.transformer.blocks.30.self_attn.attn_out
model.transformer.blocks.30.attn_norm
model.transformer.blocks.30.dropout
model.transformer.blocks.30.mlp
model.transformer.blocks.30.mlp.ff_proj
model.transformer.blocks.30.mlp.ff_out
model.transformer.blocks.30.mlp.act
model.transformer.blocks.30.ff_norm
model.transformer.blocks.31
model.transformer.blocks.31.self_attn
model.transformer.blocks.31.self_attn.att_proj
model.transformer.blocks.31.self_attn.k_norm
model.transformer.blocks.31.self_attn.q_norm
model.transformer.blocks.31.self_attn.attn_out
model.transformer.blocks.31.attn_norm
model.transformer.blocks.31.dropout
model.transformer.blocks.31.mlp
model.transformer.blocks.31.mlp.ff_proj
model.transformer.blocks.31.mlp.ff_out
model.transformer.blocks.31.mlp.act
model.transformer.blocks.31.ff_norm
model.transformer.blocks.32
model.transformer.blocks.32.self_attn
model.transformer.blocks.32.self_attn.att_proj
model.transformer.blocks.32.self_attn.k_norm
model.transformer.blocks.32.self_attn.q_norm
model.transformer.blocks.32.self_attn.attn_out
model.transformer.blocks.32.attn_norm
model.transformer.blocks.32.dropout
model.transformer.blocks.32.mlp
model.transformer.blocks.32.mlp.ff_proj
model.transformer.blocks.32.mlp.ff_out
model.transformer.blocks.32.mlp.act
model.transformer.blocks.32.ff_norm
model.transformer.blocks.33
model.transformer.blocks.33.self_attn
model.transformer.blocks.33.self_attn.att_proj
model.transformer.blocks.33.self_attn.k_norm
model.transformer.blocks.33.self_attn.q_norm
model.transformer.blocks.33.self_attn.attn_out
model.transformer.blocks.33.attn_norm
model.transformer.blocks.33.dropout
model.transformer.blocks.33.mlp
model.transformer.blocks.33.mlp.ff_proj
model.transformer.blocks.33.mlp.ff_out
model.transformer.blocks.33.mlp.act
model.transformer.blocks.33.ff_norm
model.transformer.blocks.34
model.transformer.blocks.34.self_attn
model.transformer.blocks.34.self_attn.att_proj
model.transformer.blocks.34.self_attn.k_norm
model.transformer.blocks.34.self_attn.q_norm
model.transformer.blocks.34.self_attn.attn_out
model.transformer.blocks.34.attn_norm
model.transformer.blocks.34.dropout
model.transformer.blocks.34.mlp
model.transformer.blocks.34.mlp.ff_proj
model.transformer.blocks.34.mlp.ff_out
model.transformer.blocks.34.mlp.act
model.transformer.blocks.34.ff_norm
model.transformer.blocks.35
model.transformer.blocks.35.self_attn
model.transformer.blocks.35.self_attn.att_proj
model.transformer.blocks.35.self_attn.k_norm
model.transformer.blocks.35.self_attn.q_norm
model.transformer.blocks.35.self_attn.attn_out
model.transformer.blocks.35.attn_norm
model.transformer.blocks.35.dropout
model.transformer.blocks.35.mlp
model.transformer.blocks.35.mlp.ff_proj
model.transformer.blocks.35.mlp.ff_out
model.transformer.blocks.35.mlp.act
model.transformer.blocks.35.ff_norm
model.transformer.ln_f
model.transformer.rotary_emb
model.vision_backbone
model.vision_backbone.image_vit
model.vision_backbone.image_vit.patch_embedding
model.vision_backbone.image_vit.transformer
model.vision_backbone.image_vit.transformer.resblocks
model.vision_backbone.image_vit.transformer.resblocks.0
model.vision_backbone.image_vit.transformer.resblocks.0.attention
model.vision_backbone.image_vit.transformer.resblocks.0.attention.wq
model.vision_backbone.image_vit.transformer.resblocks.0.attention.wk
model.vision_backbone.image_vit.transformer.resblocks.0.attention.wv
model.vision_backbone.image_vit.transformer.resblocks.0.attention.wo
model.vision_backbone.image_vit.transformer.resblocks.0.attention.residual_dropout
model.vision_backbone.image_vit.transformer.resblocks.0.feed_forward
model.vision_backbone.image_vit.transformer.resblocks.0.feed_forward.w1
model.vision_backbone.image_vit.transformer.resblocks.0.feed_forward.act
model.vision_backbone.image_vit.transformer.resblocks.0.feed_forward.w2
model.vision_backbone.image_vit.transformer.resblocks.0.attention_norm
model.vision_backbone.image_vit.transformer.resblocks.0.ffn_norm
model.vision_backbone.image_vit.transformer.resblocks.1
model.vision_backbone.image_vit.transformer.resblocks.1.attention
model.vision_backbone.image_vit.transformer.resblocks.1.attention.wq
model.vision_backbone.image_vit.transformer.resblocks.1.attention.wk
model.vision_backbone.image_vit.transformer.resblocks.1.attention.wv
model.vision_backbone.image_vit.transformer.resblocks.1.attention.wo
model.vision_backbone.image_vit.transformer.resblocks.1.attention.residual_dropout
model.vision_backbone.image_vit.transformer.resblocks.1.feed_forward
model.vision_backbone.image_vit.transformer.resblocks.1.feed_forward.w1

In [ ]:
model

Molmo2ForConditionalGeneration(
  (model): Molmo2Model(
    (transformer): Molmo2TextModel(
      (wte): Molmo2Embedding()
      (emb_drop): Dropout(p=0.0, inplace=False)
      (blocks): ModuleList(
        (0-35): 36 x Molmo2DecoderLayer(
          (self_attn): Molmo2Attention(
            (att_proj): Linear(in_features=4096, out_features=6144, bias=False)
            (k_norm): Molmo2RMSNorm((128,), eps=1e-06)
            (q_norm): Molmo2RMSNorm((128,), eps=1e-06)
            (attn_out): Linear(in_features=4096, out_features=4096, bias=False)
          )
          (attn_norm): Molmo2RMSNorm((4096,), eps=1e-06)
          (dropout): Dropout(p=0.0, inplace=False)
          (mlp): LanguageModelMLP(
            (ff_proj): Linear(in_features=4096, out_features=24576, bias=False)
            (ff_out): Linear(in_features=12288, out_features=4096, bias=False)
            (act): SiLUActivation()
          )
          (ff_norm): Molmo2RMSNorm((4096,), eps=1e-06)
        )
      )
      (ln_f): Molmo2RMSNorm((4096,), eps=1e-06)
      (rotary_emb): Molmo2RotaryEmbedding()
    )
    (vision_backbone): Molmo2VisionBackbone(
      (image_vit): Molmo2VisionTransformer(
        (patch_embedding): Linear(in_features=588, out_features=1152, bias=True)
        (transformer): Molmo2VisionBlockCollection(
          (resblocks): ModuleList(
            (0-24): 25 x Molmo2VisionBlock(
              (attention): ViTMultiHeadDotProductAttention(
                (wq): Linear(in_features=1152, out_features=1152, bias=True)
                (wk): Linear(in_features=1152, out_features=1152, bias=True)
                (wv): Linear(in_features=1152, out_features=1152, bias=True)
                (wo): Linear(in_features=1152, out_features=1152, bias=True)
                (residual_dropout): Dropout(p=0.0, inplace=False)
              )
              (feed_forward): ViTMLP(
                (w1): Linear(in_features=1152, out_features=4304, bias=True)
                (act): GELUTanh()
                (w2): Linear(in_features=4304, out_features=1152, bias=True)
              )
              (attention_norm): LayerNorm((1152,), eps=1e-06, elementwise_affine=True)
              (ffn_norm): LayerNorm((1152,), eps=1e-06, elementwise_affine=True)
            )
          )
        )
      )
      (image_pooling_2d): ViTMultiHeadDotProductAttention(
        (wq): Linear(in_features=2304, out_features=1152, bias=True)
        (wk): Linear(in_features=2304, out_features=1152, bias=True)
        (wv): Linear(in_features=2304, out_features=1152, bias=True)
        (wo): Linear(in_features=1152, out_features=1152, bias=True)
        (residual_dropout): Dropout(p=0.0, inplace=False)
      )
      (image_projector): ImageProjectorMLP(
        (w1): Linear(in_features=1152, out_features=12288, bias=False)
        (w2): Linear(in_features=12288, out_features=4096, bias=False)
        (w3): Linear(in_features=1152, out_features=12288, bias=False)
        (act): SiLUActivation()
      )
      (image_feature_dropout): Dropout(p=0.0, inplace=False)
    )
  )
  (lm_head): Linear(in_features=4096, out_features=151936, bias=False)
)